In [2]:
import pandas as pd   # Para manejo de datos
import numpy as np    # Para operaciones matemáticas
import matplotlib.pyplot as plt     # Para gráficos
import seaborn as sns   # Para gráficos más bonitos
import os   # Para manejo de archivos
import datetime as dt   # Para manejo de fechas
import json   # Para manejo de archivos json

In [5]:
df7 = pd.read_csv('User_reviews.csv')

In [6]:
df8 = pd.read_csv('Output_steam_games.csv')

In [7]:
df9 = pd.read_csv('User_items.csv')

In [5]:
merged_df = pd.merge(df7, df8, on='Item_Id')

In [6]:
merged_df

,User_Id,Item_Id,Recommend,Sentiment Analysis,año,Publisher,App_name,Price,Developer,Accounting,...,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing,Release_year
0,76561197970982479,1250,True,2,2011,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
1,death-hunter,1250,True,2,2015,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
2,DJKamBer,1250,True,0,2013,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
3,diego9031,1250,True,2,2015,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
4,76561198081962345,1250,True,2,2014,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41797,laislabonita75,367780,True,2,2015,Soloweb Studios,Aero's Quest,4.99,"Soloweb Studios,Ravens Eye Studio",0,...,0,0,0,0,0,0,0,0,0,2015
41798,evilindiegaming,367780,True,2,2015,Soloweb Studios,Aero's Quest,4.99,"Soloweb Studios,Ravens Eye Studio",0,...,0,0,0,0,0,0,0,0,0,2015
41799,laislabonita75,305920,False,0,2015,"ShaunJS, Digerati Distribution",Another Perspective,5.99,ShaunJS,0,...,0,0,0,0,0,0,0,0,0,2014
41800,Gamer0009,306040,True,2,2015,Antanas Marcelionis,The Howler,1.99,"Antanas Marcelionis,Renė Petrulienė",0,...,0,0,1,0,0,1,0,0,0,2016
41801,llDracuwulf,307130,True,2,2015,Legend Studio,Asteria,4.99,Legend Studio,0,...,0,0,0,0,0,0,0,0,0,2014

In [7]:
merged_df = merged_df.rename(columns={'año': 'year'})

In [8]:
merged_df

,User_Id,Item_Id,Recommend,Sentiment Analysis,year,Publisher,App_name,Price,Developer,Accounting,...,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing,Release_year
0,76561197970982479,1250,True,2,2011,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
1,death-hunter,1250,True,2,2015,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
2,DJKamBer,1250,True,0,2013,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
3,diego9031,1250,True,2,2015,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
4,76561198081962345,1250,True,2,2014,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41797,laislabonita75,367780,True,2,2015,Soloweb Studios,Aero's Quest,4.99,"Soloweb Studios,Ravens Eye Studio",0,...,0,0,0,0,0,0,0,0,0,2015
41798,evilindiegaming,367780,True,2,2015,Soloweb Studios,Aero's Quest,4.99,"Soloweb Studios,Ravens Eye Studio",0,...,0,0,0,0,0,0,0,0,0,2015
41799,laislabonita75,305920,False,0,2015,"ShaunJS, Digerati Distribution",Another Perspective,5.99,ShaunJS,0,...,0,0,0,0,0,0,0,0,0,2014
41800,Gamer0009,306040,True,2,2015,Antanas Marcelionis,The Howler,1.99,"Antanas Marcelionis,Renė Petrulienė",0,...,0,0,1,0,0,1,0,0,0,2016
41801,llDracuwulf,307130,True,2,2015,Legend Studio,Asteria,4.99,Legend Studio,0,...,0,0,0,0,0,0,0,0,0,2014

In [9]:


# Definir una función que devuelve el top 3 de desarrolladores con juegos más recomendados por usuarios para un año dado
def top_desarrolladores_recomendados(year):
    # Cargar el DataFrame de juegos
    

    # Filtrar los juegos por año
    df_year = merged_df[merged_df['year'] == year]

    # Agrupar los juegos por desarrollador y contar el número de juegos recomendados
    df_count = df_year[df_year['Recommend'] == True][df_year['Sentiment Analysis'] == 2].groupby('Developer')['App_name'].count().reset_index()

    # Ordenar los resultados por número de juegos recomendados y devolver los tres primeros desarrolladores
    top_desarrolladores = df_count.sort_values('App_name', ascending=False).head(3)['Developer'].tolist()

    # Devolver el top 3 de desarrolladores
    return top_desarrolladores
# Pedir al usuario que ingrese el año
year = input('Ingrese el año para el que desea obtener el top 3 de desarrolladores con juegos más recomendados: ')

# Convertir el año a entero
year = int(year)

# Obtener el top 3 de desarrolladores con juegos más recomendados para el año dado
top_desarrolladores = top_desarrolladores_recomendados(year)

# Imprimir el resultado
print(f"El top 1 de desarroladores para el {year} es: {top_desarrolladores[0]}, el top 2 es: {top_desarrolladores[1]}, y el top 3 es: {top_desarrolladores[2]}")

El top 1 de desarroladores para el 2015 es: Valve, el top 2 es: Facepunch Studios, y el top 3 es: Smartly Dressed Games

C:\Users\baby_\AppData\Local\Temp\ipykernel_21592\474214945.py:10: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_count = df_year[df_year['Recommend'] == True][df_year['Sentiment Analysis'] == 2].groupby('Developer')['App_name'].count().reset_index()

In [11]:
merged_df2 = pd.merge(df9,df8, on='Item_Id')

In [12]:
merged_df2

,User_Id,Items_Count,Item_Id,Item_Name,Playtime_Forever,Publisher,App_name,Price,Developer,Accounting,...,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing,Release_year
0,76561197970982479,277,10.0,Counter-Strike,6.0,Valve,Counter-Strike,9.99,Valve,0,...,0,0,0,0,0,0,0,0,0,2000
1,js41637,888,10.0,Counter-Strike,0.0,Valve,Counter-Strike,9.99,Valve,0,...,0,0,0,0,0,0,0,0,0,2000
2,Riot-Punch,328,10.0,Counter-Strike,0.0,Valve,Counter-Strike,9.99,Valve,0,...,0,0,0,0,0,0,0,0,0,2000
3,doctr,541,10.0,Counter-Strike,93.0,Valve,Counter-Strike,9.99,Valve,0,...,0,0,0,0,0,0,0,0,0,2000
4,corrupted_soul,115,10.0,Counter-Strike,108.0,Valve,Counter-Strike,9.99,Valve,0,...,0,0,0,0,0,0,0,0,0,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4215814,76561198071808318,10,444770.0,Mimpi Dreams,46.0,Silicon Jelly,Mimpi Dreams,7.99,Silicon Jelly,0,...,0,0,0,0,0,0,0,0,0,2016
4215815,76561198081168593,84,375450.0,NOBUNAGA'S AMBITION: Souzou SengokuRisshiden,51.0,"KOEI TECMO GAMES CO., LTD.",NOBUNAGA'S AMBITION: Sphere of Influence - Asc...,59.99,"KOEI TECMO GAMES CO., LTD.",0,...,0,0,0,0,0,1,0,0,0,2016
4215816,76561198101994484,139,353390.0,Alienware Steam Machine,0.0,NaN,Alienware Steam Machine,0.00,NaN,0,...,0,0,0,0,0,0,0,0,0,2015
4215817,76561198107283457,33,354280.0,ChaosTower,164.0,CashcowGames,ChaosTower,5.99,CashcowGames,0,...,0,0,1,0,0,0,0,0,0,2016
4215818,inven,3603,433920.0,Aveyond 4: Shadow Of The Mist,0.0,Degica,Aveyond 4: Shadow of the Mist,14.99,"Amaranth Games, LLC",0,...,1,0,0,0,0,0,0,0,0,2016

In [13]:
merged_df2 = merged_df2.drop(["Publisher", "Playtime_Forever"], axis=1)

In [24]:
merged_df2

,User_Id,Items_Count,Item_Id,Item_Name,App_name,Price,Developer,Accounting,Action,Adventure,...,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing,Release_year
0,76561197970982479,277,10.0,Counter-Strike,Counter-Strike,9.99,Valve,0,1,0,...,0,0,0,0,0,0,0,0,0,2000
1,js41637,888,10.0,Counter-Strike,Counter-Strike,9.99,Valve,0,1,0,...,0,0,0,0,0,0,0,0,0,2000
2,Riot-Punch,328,10.0,Counter-Strike,Counter-Strike,9.99,Valve,0,1,0,...,0,0,0,0,0,0,0,0,0,2000
3,doctr,541,10.0,Counter-Strike,Counter-Strike,9.99,Valve,0,1,0,...,0,0,0,0,0,0,0,0,0,2000
4,corrupted_soul,115,10.0,Counter-Strike,Counter-Strike,9.99,Valve,0,1,0,...,0,0,0,0,0,0,0,0,0,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4215814,76561198071808318,10,444770.0,Mimpi Dreams,Mimpi Dreams,7.99,Silicon Jelly,0,0,1,...,0,0,0,0,0,0,0,0,0,2016
4215815,76561198081168593,84,375450.0,NOBUNAGA'S AMBITION: Souzou SengokuRisshiden,NOBUNAGA'S AMBITION: Sphere of Influence - Asc...,59.99,"KOEI TECMO GAMES CO., LTD.",0,0,0,...,0,0,0,0,0,1,0,0,0,2016
4215816,76561198101994484,139,353390.0,Alienware Steam Machine,Alienware Steam Machine,0.00,NaN,0,0,0,...,0,0,0,0,0,0,0,0,0,2015
4215817,76561198107283457,33,354280.0,ChaosTower,ChaosTower,5.99,CashcowGames,0,1,0,...,0,0,1,0,0,0,0,0,0,2016
4215818,inven,3603,433920.0,Aveyond 4: Shadow Of The Mist,Aveyond 4: Shadow of the Mist,14.99,"Amaranth Games, LLC",0,0,1,...,1,0,0,0,0,0,0,0,0,2016

In [14]:
merged_df2 = merged_df2.drop(["Developer","Accounting","Action","Adventure","RPG","Racing","Simulation","Software Training","Sports","Strategy","Utilities"], axis=1)

In [15]:
merged_df2

,User_Id,Items_Count,Item_Id,Item_Name,App_name,Price,Animation &amp; Modeling,Audio Production,Casual,Design &amp; Illustration,Early Access,Education,Free to Play,Indie,Massively Multiplayer,Photo Editing,Video Production,Web Publishing,Release_year
0,76561197970982479,277,10.0,Counter-Strike,Counter-Strike,9.99,0,0,0,0,0,0,0,0,0,0,0,0,2000
1,js41637,888,10.0,Counter-Strike,Counter-Strike,9.99,0,0,0,0,0,0,0,0,0,0,0,0,2000
2,Riot-Punch,328,10.0,Counter-Strike,Counter-Strike,9.99,0,0,0,0,0,0,0,0,0,0,0,0,2000
3,doctr,541,10.0,Counter-Strike,Counter-Strike,9.99,0,0,0,0,0,0,0,0,0,0,0,0,2000
4,corrupted_soul,115,10.0,Counter-Strike,Counter-Strike,9.99,0,0,0,0,0,0,0,0,0,0,0,0,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4215814,76561198071808318,10,444770.0,Mimpi Dreams,Mimpi Dreams,7.99,0,0,0,0,0,0,0,1,0,0,0,0,2016
4215815,76561198081168593,84,375450.0,NOBUNAGA'S AMBITION: Souzou SengokuRisshiden,NOBUNAGA'S AMBITION: Sphere of Influence - Asc...,59.99,0,0,0,0,0,0,0,0,0,0,0,0,2016
4215816,76561198101994484,139,353390.0,Alienware Steam Machine,Alienware Steam Machine,0.00,0,0,0,0,0,0,0,0,0,0,0,0,2015
4215817,76561198107283457,33,354280.0,ChaosTower,ChaosTower,5.99,0,0,1,0,0,0,0,1,0,0,0,0,2016
4215818,inven,3603,433920.0,Aveyond 4: Shadow Of The Mist,Aveyond 4: Shadow of the Mist,14.99,0,0,0,0,0,0,0,1,0,0,0,0,2016

In [16]:
merged_df2 = merged_df2.drop(["Animation &amp; Modeling","Casual","Audio Production","Design &amp; Illustration","Early Access","Education","Free to Play","Indie","Massively Multiplayer","Photo Editing"], axis=1)

In [17]:
merged_df2

,User_Id,Items_Count,Item_Id,Item_Name,App_name,Price,Video Production,Web Publishing,Release_year
0,76561197970982479,277,10.0,Counter-Strike,Counter-Strike,9.99,0,0,2000
1,js41637,888,10.0,Counter-Strike,Counter-Strike,9.99,0,0,2000
2,Riot-Punch,328,10.0,Counter-Strike,Counter-Strike,9.99,0,0,2000
3,doctr,541,10.0,Counter-Strike,Counter-Strike,9.99,0,0,2000
4,corrupted_soul,115,10.0,Counter-Strike,Counter-Strike,9.99,0,0,2000
...,...,...,...,...,...,...,...,...,...
4215814,76561198071808318,10,444770.0,Mimpi Dreams,Mimpi Dreams,7.99,0,0,2016
4215815,76561198081168593,84,375450.0,NOBUNAGA'S AMBITION: Souzou SengokuRisshiden,NOBUNAGA'S AMBITION: Sphere of Influence - Asc...,59.99,0,0,2016
4215816,76561198101994484,139,353390.0,Alienware Steam Machine,Alienware Steam Machine,0.00,0,0,2015
4215817,76561198107283457,33,354280.0,ChaosTower,ChaosTower,5.99,0,0,2016
4215818,inven,3603,433920.0,Aveyond 4: Shadow Of The Mist,Aveyond 4: Shadow of the Mist,14.99,0,0,2016

In [18]:
merged_df2 = merged_df2.drop(["Video Production","Web Publishing","App_name","Items_Count","Release_year"], axis=1)

In [19]:
merged_df2

,User_Id,Item_Id,Item_Name,Price
0,76561197970982479,10.0,Counter-Strike,9.99
1,js41637,10.0,Counter-Strike,9.99
2,Riot-Punch,10.0,Counter-Strike,9.99
3,doctr,10.0,Counter-Strike,9.99
4,corrupted_soul,10.0,Counter-Strike,9.99
...,...,...,...,...
4215814,76561198071808318,444770.0,Mimpi Dreams,7.99
4215815,76561198081168593,375450.0,NOBUNAGA'S AMBITION: Souzou SengokuRisshiden,59.99
4215816,76561198101994484,353390.0,Alienware Steam Machine,0.00
4215817,76561198107283457,354280.0,ChaosTower,5.99
4215818,inven,433920.0,Aveyond 4: Shadow Of The Mist,14.99

In [56]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41802 entries, 0 to 41801
Data columns (total 32 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   User_Id                    41802 non-null  object
 1   Item_Id                    41802 non-null  int64
 2   Recommend                  41802 non-null  bool
 3   Sentiment Analysis         41802 non-null  int64
 4   year                       41802 non-null  int64
 5   Publisher                  41159 non-null  object
 6   App_name                   41802 non-null  object
 7   Price                      41222 non-null  float64
 8   Developer                  41555 non-null  object
 9   Accounting                 41802 non-null  int64
 10  Action                     41802 non-null  int64
 11  Adventure                  41802 non-null  int64
 12  Animation &amp; Modeling   41802 non-null  int64
 13  Audio Production           41802 non-null  int64
 14  Casual                     41802 non-null  int64
 15  Design &amp; Illustration  41802 non-null  int64
 16  Early Access               41802 non-null  int64
 17  Education                  41802 non-null  int64
 18  Free to Play               41802 non-null  int64
 19  Indie                      41802 non-null  int64
 20  Massively Multiplayer      41802 non-null  int64
 21  Photo Editing              41802 non-null  int64
 22  RPG                        41802 non-null  int64
 23  Racing                     41802 non-null  int64
 24  Simulation                 41802 non-null  int64
 25  Software Training          41802 non-null  int64
 26  Sports                     41802 non-null  int64
 27  Strategy                   41802 non-null  int64
 28  Utilities                  41802 non-null  int64
 29  Video Production           41802 non-null  int64
 30  Web Publishing             41802 non-null  int64
 31  Release_year               41802 non-null  int64
dtypes: bool(1), float64(1), int64(26), object(4)
memory usage: 9.9+ MB

In [20]:
merged_df2['User_Id'] = merged_df2['User_Id'].astype(str)

In [21]:
# Define el DataFrame como una variable global
df = merged_df2

def calcular_suma_compras_por_id(item_id):
    # Convierte el ID a una cadena si es un entero
    if type(item_id) == int:
        item_id = str(item_id)

    # Filtra el DataFrame por el ID especificado
    df_filtrado = df[df['User_Id'] == item_id]

    # Verifica si el DataFrame contiene datos para el ID especificado
    if df_filtrado.empty:
        print(f"No se encontraron datos para el ID {item_id}.")
        return None

    # Calcula la suma de compras para el ID especificado
    suma_compras = df_filtrado['Price'].sum()

    # Imprime la suma de compras para el ID especificado
    print(f"La suma de compras para el ID {item_id} es: {suma_compras}")

    # Devuelve la suma de compras
    return suma_compras

In [22]:
calcular_suma_compras_por_id(76561197970982479)

La suma de compras para el ID 76561197970982479 es: 3419.3200000000006

3419.3200000000006

In [23]:
df69 = df7[['Item_Id', 'Recommend']]

In [ ]:
merged_df4 = pd.merge(df69[['Item_Id', 'User_Id', 'Price']], df[['Item_Id', 'Recommend']], on='Item_Id', how='inner')

In [73]:
df69

       Item_Id  Recommend
0         1250       True
1        22200       True
2        43110       True
3       251610       True
4       227300       True
...        ...        ...
49181      730       True
49182   253980       True
49183      730       True
49184      730       True
49185   369200       True

[49186 rows x 2 columns]

In [ ]:
def userdata(user_id):
    # Filtrar los datos para el usuario especificado
    user_data = df[df['user_id'] == user_id]

    user_items = items[items['user_id'] == user_id]

    # Calcular la cantidad de dinero gastado por el usuario
    dinero_gastado = user_data['price'].sum()

    # Calcular el porcentaje de recomendación en base a reviews.recommend
    recomendacion = user_data['recommend'].sum()
    porcentaje_recomendacion = recomendacion / len(user_data) * 100

    # Calcular la cantidad de items
    cantidad_de_items = user_items['item_id'].nunique()

    # Crear un diccionario con los resultados
    resultados = {
        'Cantidad de dinero gastado': dinero_gastado,
        'Porcentaje de recomendación': porcentaje_recomendacion,
        'Cantidad de items': cantidad_de_items
    }

    return resultados

In [32]:
df

,User_Id,Item_Id,Item_Name,Price
0,76561197970982479,10.0,Counter-Strike,9.99
1,js41637,10.0,Counter-Strike,9.99
2,Riot-Punch,10.0,Counter-Strike,9.99
3,doctr,10.0,Counter-Strike,9.99
4,corrupted_soul,10.0,Counter-Strike,9.99
...,...,...,...,...
4215814,76561198071808318,444770.0,Mimpi Dreams,7.99
4215815,76561198081168593,375450.0,NOBUNAGA'S AMBITION: Souzou SengokuRisshiden,59.99
4215816,76561198101994484,353390.0,Alienware Steam Machine,0.00
4215817,76561198107283457,354280.0,ChaosTower,5.99
4215818,inven,433920.0,Aveyond 4: Shadow Of The Mist,14.99

In [30]:


def userdata(User_id):
    # Filtrar los datos para el usuario especificado
    user_data = df[df['User_Id'] == User_id]

    user_items = df9[df9['User_Id'] == User_id]

    # Calcular la cantidad de dinero gastado por el usuario
    dinero_gastado = user_data['Price'].sum()

    # Calcular el porcentaje de recomendación en base a reviews.recommend
    recomendacion = user_data['Recommend'].sum()
    porcentaje_recomendacion = recomendacion / len(user_data) * 100

    # Calcular la cantidad de items
    cantidad_de_items = user_items['Item_Id'].nunique()

    # Crear un diccionario con los resultados
    resultados = {
        'Cantidad de dinero gastado': dinero_gastado,
        'Porcentaje de recomendación': porcentaje_recomendacion,
        'Cantidad de items': cantidad_de_items
    }

    return resultados

In [33]:
merged_df

,User_Id,Item_Id,Recommend,Sentiment Analysis,year,Publisher,App_name,Price,Developer,Accounting,...,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing,Release_year
0,76561197970982479,1250,True,2,2011,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
1,death-hunter,1250,True,2,2015,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
2,DJKamBer,1250,True,0,2013,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
3,diego9031,1250,True,2,2015,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
4,76561198081962345,1250,True,2,2014,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41797,laislabonita75,367780,True,2,2015,Soloweb Studios,Aero's Quest,4.99,"Soloweb Studios,Ravens Eye Studio",0,...,0,0,0,0,0,0,0,0,0,2015
41798,evilindiegaming,367780,True,2,2015,Soloweb Studios,Aero's Quest,4.99,"Soloweb Studios,Ravens Eye Studio",0,...,0,0,0,0,0,0,0,0,0,2015
41799,laislabonita75,305920,False,0,2015,"ShaunJS, Digerati Distribution",Another Perspective,5.99,ShaunJS,0,...,0,0,0,0,0,0,0,0,0,2014
41800,Gamer0009,306040,True,2,2015,Antanas Marcelionis,The Howler,1.99,"Antanas Marcelionis,Renė Petrulienė",0,...,0,0,1,0,0,1,0,0,0,2016
41801,llDracuwulf,307130,True,2,2015,Legend Studio,Asteria,4.99,Legend Studio,0,...,0,0,0,0,0,0,0,0,0,2014

In [34]:
merged_df5 = merged_df[['User_Id', 'Price','Recommend','Item_Id']]

In [35]:
merged_df5

                 User_Id  Price  Recommend  Item_Id
0      76561197970982479  19.99       True     1250
1           death-hunter  19.99       True     1250
2               DJKamBer  19.99       True     1250
3              diego9031  19.99       True     1250
4      76561198081962345  19.99       True     1250
...                  ...    ...        ...      ...
41797     laislabonita75   4.99       True   367780
41798    evilindiegaming   4.99       True   367780
41799     laislabonita75   5.99      False   305920
41800          Gamer0009   1.99       True   306040
41801        llDracuwulf   4.99       True   307130

[41802 rows x 4 columns]

In [63]:
def userdata(user_id):
    
    if type(user_id) == int:
        user_id = str(user_id)

    
    if not user_id in merged_df5['User_Id'].values or not user_id in df9['User_Id'].values:
        return f"El user_id {user_id} no existe en la base de datos u.u."

    user_data = merged_df5[merged_df5['User_Id'] == user_id]

    user_items = df9[df9['User_Id'] == user_id]

    # Calcular la cantidad de dinero gastado por el usuario
    dinero_gastado = user_data['Price'].sum()

    # Calcular el porcentaje de recomendación en base a reviews.recommend
    recomendacion = user_data['Recommend'].sum()
    porcentaje_recomendacion = recomendacion / len(user_data) * 100

    # Calcular la cantidad de items
    cantidad_de_items = user_items['Item_Id'].nunique()

    # Crear un diccionario con los resultados
    resultados = {
        'Cantidad de dinero gastado': dinero_gastado,
        'Porcentaje de recomendación': porcentaje_recomendacion,
        'Cantidad de items': cantidad_de_items
    }

    return resultados

In [65]:
userdata('kk')

'El user_id kk no existe en la base de datos u.u.'

In [60]:
hola = merged_df5[merged_df5['User_Id'] == '76561197970982479']

In [61]:
hola

               User_Id  Price  Recommend  Item_Id
0    76561197970982479  19.99       True     1250
319  76561197970982479   9.99       True    22200

In [9]:
def UserForGenre(genero):
    if not genero in df_nuevo.columns:
        return f"El género {genero} no existe en la base de datos."
    
    df_genre = df_nuevo[df_nuevo[genero] == 1]

    usur_mas_horas = df_genre.groupby("User_Id")["Playtime_Forever"].sum().idxmax()

    filtro_usur = df_genre[df_genre["User_Id"] == usur_mas_horas]

    horas_jugXaño = filtro_usur.groupby("Release_year")["Playtime_Forever"].sum()

    registro = horas_jugXaño.to_dict()

    Horas_por_año = {}
    for clave, valor in registro.items():
        clave_formateada = f'Año: {int(clave)}'
        valor_formateado = int(valor)
        Horas_por_año[clave_formateada] = valor_formateado

    return {"Usuario con más horas jugadas": usur_mas_horas, "Horas jugadas por año": Horas_por_año}

In [8]:
merged_df10 = pd.merge(df8, df9, on='Item_Id')
df_nuevo = merged_df10.drop(columns=["Item_Id","App_name","Price","Developer","Items_Count","Item_Name"])

In [10]:
UserForGenre('Action')

{'Usuario con más horas jugadas': 'Sp3ctre',
 'Horas jugadas por año': {'Año: 1993': 0,
  'Año: 1995': 217,
  'Año: 1996': 0,
  'Año: 1998': 0,
  'Año: 1999': 44,
  'Año: 2000': 70644,
  'Año: 2001': 13,
  'Año: 2002': 238,
  'Año: 2003': 7673,
  'Año: 2004': 127411,
  'Año: 2005': 21339,
  'Año: 2006': 896,
  'Año: 2007': 112784,
  'Año: 2008': 224,
  'Año: 2009': 108326,
  'Año: 2010': 78083,
  'Año: 2011': 154896,
  'Año: 2012': 378296,
  'Año: 2013': 120461,
  'Año: 2014': 130691,
  'Año: 2015': 312511,
  'Año: 2016': 29576,
  'Año: 2017': 43327}}

In [11]:
df_merged123 = pd.merge(df8, df7, on='Item_Id')

In [14]:
df_merged123.value_counts()

Publisher        App_name                          Price  Item_Id  Developer        Accounting  Action  Adventure  Animation &amp; Modeling  Audio Production  Casual  Design &amp; Illustration  Early Access  Education  Free to Play  Indie  Massively Multiplayer  Photo Editing  RPG  Racing  Simulation  Software Training  Sports  Strategy  Utilities  Video Production  Web Publishing  Release_year  User_Id            Recommend  Sentiment Analysis  año
Telltale Games   The Walking Dead: Season 2        24.99  261030   Telltale Games   0           0       1          0                         0                 0       0                          0             0          0             0      0                      0              0    0       0           0                  0       0         0          0                 0               2013          76561198045953692  True       0                   2014    3
Valve            Counter-Strike: Global Offensive  14.99  730      Valve            0           1       0          0                         0                 0       0                          0             0          0             0      0                      0              0    0       0           0                  0       0         0          0                 0               2012          blablabla174       True       2                   2015    3
The Indie Stone  Project Zomboid                   14.99  108600   The Indie Stone  0           0       0          0                         0                 0       0                          1             0          0             1      0                      0              1    0       1           0                  0       0         0          0                 0               2013          76561198051777058  True       2                   2014    3
Re-Logic         Terraria                          9.99   105600   Re-Logic         0           1       1          0                         0                 0       0                          0             0          0             1      0                      0              1    0       0           0                  0       0         0          0                 0               2011          76561198027488037  True       0                   2015    3
Jagex            Ace of Spades: Battle Builder     14.99  224540   Jagex Limited    0           1       0          0                         0                 0       0                          0             0          0             1      0                      0              0    0       0           0                  0       0         0          0                 0               2012          76561198100326818  True       2                   2014    3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ..
Hardsuit Labs    Blacklight: Retribution           0.00   209870   Hardsuit Labs    0           1       0          0                         0                 0       0                          0             0          1             0      0                      0              0    0       0           0                  0       0         0          0                 0               2012          Hasam1             True       2                   2015    1
                                                                                                                                                                                                                                                                                                                                                                                                               Hydroflame564      True       2                   2015    1
                                                                                                                                                                                                                                                                                                                                                                                                               ImUnkS             True       2                   2013    1
                                                                                                                                                                                                                                                                                                                                                                                                               Jozav              True       2                   2012    1
webgames         Gunslingers                       0.00   416670   webgames         0           0       0          0                         0                 0       0                          1             0          1             0      0                      0              0    0       0           0                  0       1         0          0                 0               2015          76561198021814659  False      2                   2015    1
Name: count, Length: 39969, dtype: int64

In [ ]:
def top_desarrolladores_recomendados(year):
    # Cargar el DataFrame de juegos
    

    # Filtrar los juegos por año
    df_year = merged_df[merged_df['year'] == year]

    # Agrupar los juegos por desarrollador y contar el número de juegos recomendados
    df_count = df_year[df_year['Recommend'] == True][df_year['Sentiment Analysis'] == 2].groupby('Developer')['App_name'].count().reset_index()

    # Ordenar los resultados por número de juegos recomendados y devolver los tres primeros desarrolladores
    top_desarrolladores = df_count.sort_values('App_name', ascending=False).head(3)['Developer'].tolist()

    # Devolver el top 3 de desarrolladores
    return top_desarrolladores