In [2]:
import pandas as pd    # Para manejo de datos
import numpy as np    # Para operaciones matemáticas
import matplotlib.pyplot as plt     # Para gráficos
import seaborn as sns   # Para gráficos más bonitos
import os   # Para manejo de archivos
import datetime as dt   # Para manejo de fechas
import json   # Para manejo de archivos json
from typing import List, Dict, Tuple, Sequence, Any, Union, Optional, Callable   # Para definir tipos de datos

In [7]:
df7 = pd.read_csv('User_reviews.csv')
df8 = pd.read_csv('Output_steam_games.csv')
df9 = pd.read_csv('User_items.csv')
merged_df = pd.merge(df7, df8, on='Item_Id')
merged_df = merged_df.rename(columns={'año': 'year'})

In [3]:
def top_desarrolladores_recomendados(year):
    # Cargar el DataFrame de juegos
    

    # Filtrar los juegos por año
    df_year = merged_df[merged_df['year'] == year]

    # Agrupar los juegos por desarrollador y contar el número de juegos recomendados
    df_count = df_year[df_year['Recommend'] == True][df_year['Sentiment Analysis'] == 2].groupby('Developer')['App_name'].count().reset_index()

    # Ordenar los resultados por número de juegos recomendados y devolver los tres primeros desarrolladores
    top_desarrolladores = df_count.sort_values('App_name', ascending=False).head(3)['Developer'].tolist()

    # Devolver el top 3 de desarrolladores
    return print(f"El top 1 de desarroladores para el {year} es: {top_desarrolladores[0]}, el top 2 es: {top_desarrolladores[1]}, y el top 3 es: {top_desarrolladores[2]}")

In [ ]:
import pandas as pd

reviews=pd.read_csv("reviews.csv")
items=pd.read_csv("items.csv")
games=pd.read_csv("games.csv")

merged_reviews_games = reviews.merge(games[['item_id', 'price']])


def userdata(user_id):
    # Filtrar los datos para el usuario especificado
    user_data = merged_reviews_games[merged_reviews_games['user_id'] == user_id]

    user_items = df9[df9['user_id'] == user_id]

    # Calcular la cantidad de dinero gastado por el usuario
    dinero_gastado = user_data['price'].sum()

    # Calcular el porcentaje de recomendación en base a reviews.recommend
    recomendacion = user_data['recommend'].sum()
    porcentaje_recomendacion = recomendacion / len(user_data) * 100

    # Calcular la cantidad de items
    cantidad_de_items = user_items['item_id'].nunique()

    # Crear un diccionario con los resultados
    resultados = {
        'Cantidad de dinero gastado': dinero_gastado,
        'Porcentaje de recomendación': porcentaje_recomendacion,
        'Cantidad de items': cantidad_de_items
    }

    return resultados

In [5]:
import pandas as pd

df7=pd.read_csv("reviews.csv")
df9=pd.read_csv("items.csv")
df8=pd.read_csv("games.csv")

merged_reviews_games = reviews.merge(games[['item_id', 'price']])


def userdata(user_id):
    # Filtrar los datos para el usuario especificado
    user_data = merged_reviews_games[merged_reviews_games['user_id'] == user_id]

    user_items = items[items['user_id'] == user_id]

    # Calcular la cantidad de dinero gastado por el usuario
    dinero_gastado = user_data['price'].sum()

    # Calcular el porcentaje de recomendación en base a reviews.recommend
    recomendacion = user_data['recommend'].sum()
    porcentaje_recomendacion = recomendacion / len(user_data) * 100

    # Calcular la cantidad de items
    cantidad_de_items = user_items['item_id'].nunique()

    # Crear un diccionario con los resultados
    resultados = {
        'Cantidad de dinero gastado': dinero_gastado,
        'Porcentaje de recomendación': porcentaje_recomendacion,
        'Cantidad de items': cantidad_de_items
    }

    return resultados



@app.get("/user/{user_id}")
async def user(user_id: str):
    try:
        result = userdata(user_id)
        return result
    except Exception as e:
        return {"error": str(e)}

FileNotFoundError: [Errno 2] No such file or directory: 'reviews.csv'

In [ ]:
df7 = pd.read_csv('User_reviews.csv')
df8 = pd.read_csv('Output_steam_games.csv')
df9 = pd.read_csv('User_items.csv')
merged_df = pd.merge(df7, df8, on='Item_Id')
merged_df = merged_df.rename(columns={'año': 'year'})
merged_df5 = merged_df[['User_Id', 'Price','Recommend','Item_Id']]

In [3]:
df7 = pd.read_csv('User_reviews.csv')
df8 = pd.read_csv('Output_steam_games.csv')
df9 = pd.read_csv('User_items.csv')

In [5]:
merged_df10 = pd.merge(df8, df9, on='Item_Id')
df_nuevo = merged_df10.drop(columns=["Item_Id","App_name","Price","Developer","Items_Count","Item_Name"])

In [7]:
df_nuevo.info(["year"])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4215819 entries, 0 to 4215818
Data columns (total 26 columns):
 #   Column                     Dtype
---  ------                     -----
 0   Publisher                  object
 1   Accounting                 int64
 2   Action                     int64
 3   Adventure                  int64
 4   Animation &amp; Modeling   int64
 5   Audio Production           int64
 6   Casual                     int64
 7   Design &amp; Illustration  int64
 8   Early Access               int64
 9   Education                  int64
 10  Free to Play               int64
 11  Indie                      int64
 12  Massively Multiplayer      int64
 13  Photo Editing              int64
 14  RPG                        int64
 15  Racing                     int64
 16  Simulation                 int64
 17  Software Training          int64
 18  Sports                     int64
 19  Strategy                   int64
 20  Utilities                  int64
 21  Video Production           int64
 22  Web Publishing             int64
 23  Release_year               int64
 24  User_Id                    object
 25  Playtime_Forever           float64
dtypes: float64(1), int64(23), object(2)
memory usage: 836.3+ MB

In [14]:
#df = pd.read_csv(r"PI_ML_OPS\clean_steam_games")
#df3 = pd.read_csv(r"PI_ML_OPS\clean_items")
#merged_df10 = pd.merge(df8, df9, on='Item_Id')
#df_marge_item = pd.merge(df , df3,on="item_id" )

#df_nuevo = df_marge_item.drop(columns=["item_id","app_name","price","developer","items_count","item_name"])

def UserForGenre(genero):
    if not genero in df_nuevo.columns:
        return f"El género {genero} no existe en el DataFrame."
    
    df_genre = df_nuevo[df_nuevo[genero] == 1] #llamo el genero

    usur_mas_horas = df_genre.groupby("User_Id")["Playtime_Forever"].sum().idxmax() #usuario con más horas de juego en el genero

    filtro_usur = df_genre[df_genre["User_Id"] == usur_mas_horas] #filtramos por el usuario con mas horas jugadas

    horas_jugXaño = filtro_usur.groupby("Release_year")["Playtime_Forever"].sum() #horas jugadas por año 

    registro = horas_jugXaño.to_dict() #paso las horas por año en diccionario

    Horas_por_año = {}  #creo un diccionario vacio para guardar registros 
    for clave, valor in registro.items(): #un for para que vaya iterando por cada item
        clave_formateada = f'Año: {int(clave)}' #formateo para que me salga con año
        valor_formateado = f'Horas: {int(valor)}' #formateo para que me salga con horas
        Horas_por_año[clave_formateada] = valor_formateado 

    return f"Usuario con más horas jugadas para Género {genero} : ,{usur_mas_horas} Horas jugadas:{Horas_por_año}"

In [15]:
UserForGenre("Action")

"Usuario con más horas jugadas para Género Action : ,Sp3ctre Horas jugadas:{'Año: 1993': 'Horas: 0', 'Año: 1995': 'Horas: 217', 'Año: 1996': 'Horas: 0', 'Año: 1998': 'Horas: 0', 'Año: 1999': 'Horas: 44', 'Año: 2000': 'Horas: 70644', 'Año: 2001': 'Horas: 13', 'Año: 2002': 'Horas: 238', 'Año: 2003': 'Horas: 7673', 'Año: 2004': 'Horas: 127411', 'Año: 2005': 'Horas: 21339', 'Año: 2006': 'Horas: 896', 'Año: 2007': 'Horas: 112784', 'Año: 2008': 'Horas: 224', 'Año: 2009': 'Horas: 108326', 'Año: 2010': 'Horas: 78083', 'Año: 2011': 'Horas: 154896', 'Año: 2012': 'Horas: 378296', 'Año: 2013': 'Horas: 120461', 'Año: 2014': 'Horas: 130691', 'Año: 2015': 'Horas: 312511', 'Año: 2016': 'Horas: 29576', 'Año: 2017': 'Horas: 43327'}"

In [ ]:
def UserForGenre(genero):
    df_genre = df_nuevo[df_nuevo[genero] == 1] #llamo el genero

    usur_mas_horas = df_genre.groupby("User_Id")["Playtime_forever"].sum().idxmax() #usuario con más horas de juego en el genero

    filtro_usur = df_genre[df_genre["User_Id"] == usur_mas_horas] #filtramos por el usuario con mas horas jugadas

    horas_jugXaño = filtro_usur.groupby("Release_year")["playtime_forever"].sum() #horas jugadas por año 

    registro = horas_jugXaño.to_dict() #paso las horas por año en diccionario

    Horas_por_año = {}  #creo un diccionario vacio para guardar registros 
    for clave, valor in registro.items(): #un for para que vaya iterando por cada item
        clave_formateada = f'Año: {int(clave)}' #formateo para que me salga con año
        valor_formateado = f'Horas: {int(valor)}' #formateo para que me salga con horas
        Horas_por_año[clave_formateada] = valor_formateado 

    return print(f"Usuario con más horas jugadas para Género {genero} : ,{usur_mas_horas} Horas jugadas:{Horas_por_año}")

In [16]:
df8

,Publisher,App_name,Price,Item_Id,Developer,Accounting,Action,Adventure,Animation &amp; Modeling,Audio Production,...,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing,Release_year
0,Kotoshiro,Lost Summoner Kitty,4.99,761140,Kotoshiro,0,1,0,0,0,...,0,0,1,0,0,1,0,0,0,2018
1,"Making Fun, Inc.",Ironbound,0.00,643980,Secret Level SRL,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,2018
2,Poolians.com,Real Pool 3D - Poolians,0.00,670290,Poolians.com,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,2017
3,彼岸领域,弹炸人2222,0.99,767400,彼岸领域,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,2017
4,Trickjump Games Ltd,Battle Royale Trainer,3.99,772540,Trickjump Games Ltd,0,1,1,0,0,...,0,0,1,0,0,0,0,0,0,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29961,Bidoniera Games,Kebab it Up!,1.99,745400,Bidoniera Games,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,2018
29962,Ghost_RUS Games,Colony On Mars,1.99,773640,"Nikita ""Ghost_RUS""",0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,2018
29963,Sacada,LOGistICAL: South Africa,4.99,733530,Sacada,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,2018
29964,Laush Studio,Russian Roads,1.99,610660,Laush Dmitriy Sergeevich,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,2018
29965,SIXNAILS,EXIT 2 - Directions,4.99,658870,"xropi,stev3ns",0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2017

In [ ]:
df_nuevo = df[["item_id", "price","developer","Año_lanzamiento"]] #columnas que voy a utilizar
def developer(desarrollador):
    df_deve = df[df["developer"] == desarrollador] #llamo al desarrollador

    cant_item = df_deve.groupby("Año_lanzamiento")["item_id"].count() #obtengo la cantidad por año 

    Free = df_deve[df_deve["price"] == 0] #juegos gratuitos del desarrollador

    total_free = Free.groupby("Año_lanzamiento")["price"].count() #cantidad de gratis por año 

    cont_free_año = round((total_free/cant_item)*100,2) #porcentaje por free por año 

    #asigno nombre a las series
    cant_item.name = "Cantidad de Items"

    cont_free_año.name = "Contenido Free"

    tabla = pd.merge(cant_item, cont_free_año,on="Año_lanzamiento") #unimos las dos tablas para hacerla unica
    #var = pd.cont_free_año(["Año_lanzamiento","item_id"])

    return tabla

In [11]:
df_f1 = df8[["Item_Id", "Price","Developer","Release_year"]] #tabla que utilizo en la funcion 1
def developer(desarrollador):
    df_deve = df_f1[df_f1["Developer"] == desarrollador] #llamo al desarrollador

    cant_item = df_deve.groupby("Release_year")["Item_Id"].count() #obtengo la cantidad por año 

    Free = df_deve[df_deve["Price"] == 0] #juegos gratuitos del desarrollador

    total_free = Free.groupby("Release_year")["Price"].count() #cantidad de gratis por año 

    cont_free_año = round((total_free/cant_item)*100,2) #porcentaje por free por año 

    #asigno nombre a las series
    cant_item.name = "Cantidad de Items"

    cont_free_año.name = "Contenido Free"

    tabla = pd.merge(cant_item, cont_free_año,on="Release_year") #unimos las dos tablas para hacerla unica
    #var = pd.cont_free_año(["Año_lanzamiento","item_id"])

    tabla['Contenido Free'] = tabla['Contenido Free'].apply(lambda x: f"{x}%" if not pd.isna(x) else x)

    tabla = tabla.dropna()

    tabla = tabla.reset_index()

    return tabla

In [12]:
developer("Valve")

              Cantidad de Items Contenido Free
Release_year
2007                          3         33.33%
2010                          2          50.0%
2016                          1         100.0%

In [ ]:
@app.get("/developers/{developer_name}")
async def get_developer_data(developer_name: str):
    # Obtener los datos del desarrollador
    developer_data = developer(developer_name)

    # Convertir la tabla de Pandas a una lista de diccionarios
    developer_list = developer_data.to_dict(orient="records")

    # Devolver el resultado como respuesta JSON
    return developer_list

In [ ]:
from fastapi import FastAPI
from typing import List
import pandas as pd

app = FastAPI()

# Cargar los datos del archivo CSV
df_f1 = pd.read_csv("nombre_del_archivo.csv")

# Definir la ruta para obtener los datos del desarrollador
@app.get("/developers/{developer_name}")
async def get_developer_data(developer_name: str):
    # Obtener los datos del desarrollador
    developer_data = developer(developer_name)

    # Convertir la tabla de Pandas a una lista de diccionarios
    developer_list = developer_data.to_dict(orient="records")

    # Devolver el resultado como respuesta JSON
    return developer_list

# Definir la función para obtener los datos del desarrollador
def developer(developer_name: str):
    # Filtrar los datos del DataFrame por el nombre del desarrollador
    developer_data = df_f1[df_f1["Developer"] == developer_name]

    # Agrupar los datos por año de lanzamiento y contar la cantidad de juegos
    games_per_year = developer_data.groupby("Release_year")["Item_Id"].count()

    # Filtrar los juegos gratuitos del desarrollador y contar la cantidad por año
    free_games = developer_data[developer_data["Price"] == 0]
    free_games_per_year = free_games.groupby("Release_year")["Item_Id"].count()

    # Calcular el porcentaje de juegos gratuitos por año
    free_percentage_per_year = round((free_games_per_year / games_per_year) * 100, 2)

    # Crear una tabla con los resultados
    table = pd.concat([games_per_year, free_percentage_per_year], axis=1)
    table.columns = ["Cantidad de juegos", "Porcentaje de juegos gratuitos"]

    # Eliminar las filas con valores NaN
    table = table.dropna()

    # Agregar el signo de porcentaje a la columna "Porcentaje de juegos gratuitos"
    table["Porcentaje de juegos gratuitos"] = table["Porcentaje de juegos gratuitos"].apply(lambda x: f"{x}%" if not pd.isna(x) else x)

    return table

In [9]:
def developer(developer_name: str):
    # Filtrar los datos del DataFrame por el nombre del desarrollador
    developer_data = df_f1[df_f1["Developer"] == developer_name]

    # Agrupar los datos por año de lanzamiento y contar la cantidad de juegos
    games_per_year = developer_data.groupby("Release_year")["Item_Id"].count()

    # Filtrar los juegos gratuitos del desarrollador y contar la cantidad por año
    free_games = developer_data[developer_data["Price"] == 0]
    free_games_per_year = free_games.groupby("Release_year")["Item_Id"].count()

    # Calcular el porcentaje de juegos gratuitos por año
    free_percentage_per_year = round((free_games_per_year / games_per_year) * 100, 2)

    # Crear una tabla con los resultados
    table = pd.concat([games_per_year, free_percentage_per_year], axis=1)
    table.columns = ["Cantidad de juegos", "Porcentaje de juegos gratuitos"]

    # Eliminar las filas con valores NaN
    table = table.dropna()

    # Agregar el signo de porcentaje a la columna "Porcentaje de juegos gratuitos"
    table["Porcentaje de juegos gratuitos"] = table["Porcentaje de juegos gratuitos"].apply(lambda x: f"{x}%" if not pd.isna(x) else x)

    return table

In [10]:
developer("Valve")

NameError: name 'df_f1' is not defined

In [52]:
from fastapi import FastAPI
import pandas as pd

app = FastAPI()



# Definir la ruta para obtener los datos del desarrollador
@app.get("/developers/{developer_name}")
async def get_developer_data(developer_name: str):
    # Obtener los datos del desarrollador
    developer_data = developer(developer_name)

    # Devolver el resultado como respuesta JSON
    return developer_data.to_dict()

# Definir la función para obtener los datos del desarrollador
def developer(developer_name: str):
    # Filtrar los datos del DataFrame por el nombre del desarrollador
    developer_data = df_f1[df_f1["Developer"] == developer_name]

    # Agrupar los datos por año de lanzamiento y contar la cantidad de juegos
    games_per_year = developer_data.groupby("Release_year")["Item_Id"].count()

    # Filtrar los juegos gratuitos del desarrollador y contar la cantidad por año
    free_games = developer_data[developer_data["Price"] == 0]
    free_games_per_year = free_games.groupby("Release_year")["Item_Id"].count()

    # Calcular el porcentaje de juegos gratuitos por año
    free_percentage_per_year = round((free_games_per_year / games_per_year) * 100, 2)

    # Crear una tabla con los resultados
    table = pd.concat([games_per_year, free_percentage_per_year], axis=1)
    table.columns = ["Cantidad de juegos", "Porcentaje de juegos gratuitos"]

    # Eliminar las filas con valores NaN
    table = table.dropna()

    # Agregar el signo de porcentaje a la columna "Porcentaje de juegos gratuitos"
    table["Porcentaje de juegos gratuitos"] = table["Porcentaje de juegos gratuitos"].apply(lambda x: f"{x}%" if not pd.isna(x) else x)

    return table

FileNotFoundError: [Errno 2] No such file or directory: 'nombre_del_archivo.csv'

In [ ]:
@app.get("/developer/{desarrollador}")
async def get_developer_info(desarrollador: str):
    # Asume que df ya está cargado y disponible aquí
    tabla = developer(desarrollador)
    return tabla.to_dict(orient="split")

In [ ]:
@app.get("/developers/{developer_name}")
async def get_developer_data(developer_name: str):
    # Obtener los datos del desarrollador
    developer_data = developer(developer_name)

    # Devolver el resultado como respuesta CSV
    return CSVResponse(developer_data.to_csv(index=False))

In [25]:
df9.columns.tolist()

['User_Id', 'Items_Count', 'Item_Id', 'Item_Name', 'Playtime_Forever']

In [26]:
df_merged123 = pd.merge(df8, df7, on='Item_Id')

In [27]:
df_merged123.columns.tolist()

['Publisher',
 'App_name',
 'Price',
 'Item_Id',
 'Developer',
 'Accounting',
 'Action',
 'Adventure',
 'Animation &amp; Modeling',
 'Audio Production',
 'Casual',
 'Design &amp; Illustration',
 'Early Access',
 'Education',
 'Free to Play',
 'Indie',
 'Massively Multiplayer',
 'Photo Editing',
 'RPG',
 'Racing',
 'Simulation',
 'Software Training',
 'Sports',
 'Strategy',
 'Utilities',
 'Video Production',
 'Web Publishing',
 'Release_year',
 'User_Id',
 'Recommend',
 'Sentiment Analysis',
 'año']

In [28]:
df_limpio = df_merged123[['User_Id', 'Item_Id','Developer','Release_year','Sentiment Analysis']]

In [ ]:
df_merged123 = pd.merge(df9, df8, on='Item_Id') 

df_merged123 = df_merged123[['User_Id', 'Item_Id','Developer','Release_year','Sentiment Analysis']]

In [33]:

def developer_reviews_analysis(desarrolladora:str):
    
    # Se filtran las columnas a utilizar y se eliminan duplicados
    df_merged = df_limpio[['User_Id', 'Item_Id','Developer','Release_year','Sentiment Analysis']]


    df_merged = df_merged[df_merged["Developer"] == desarrolladora]

    # Se obtienen la cantidad de reviews positivas y negativas
    positive_reviews = df_merged[df_merged["Sentiment Analysis"] == 2].shape[0]
    negative_reviews = df_merged[df_merged["Sentiment Analysis"] == 0].shape[0]

    # Se crea un string con el resumen de las reviews
    resumen_reviews = f"[Negative = {negative_reviews}, Positive = {positive_reviews}]"

    # Se crea un diccionario con el resumen de las reviews
    dicc = {desarrolladora : resumen_reviews}

    # Se devuelve un diccionario con los resultados obtenidos
    return dicc

In [34]:
developer_reviews_analysis("Valve")

{'Valve': '[Negative = 823, Positive = 5761]'}

In [35]:
def UserForGenre(genero):
    if not genero in df_nuevo.columns:
        return f"El género {genero} no existe en la base de datos."
    
    df_genre = df_nuevo[df_nuevo[genero] == 1]

    usur_mas_horas = df_genre.groupby("User_Id")["Playtime_Forever"].sum().idxmax()

    filtro_usur = df_genre[df_genre["User_Id"] == usur_mas_horas]

    horas_jugXaño = filtro_usur.groupby("Release_year")["Playtime_Forever"].sum()

    registro = horas_jugXaño.to_dict()

    Horas_por_año = {}
    for clave, valor in registro.items():
        clave_formateada = f'Año: {int(clave)}'
        valor_formateado = int(valor)
        Horas_por_año[clave_formateada] = valor_formateado

    return {"Usuario con más horas jugadas": usur_mas_horas, "Horas jugadas por año": Horas_por_año}

In [36]:
UserForGenre("Action")

NameError: name 'df_nuevo' is not defined

In [37]:
def developer(developer_name: str):
    # Filtrar los datos del DataFrame por el nombre del desarrollador
    developer_data = df_f1[df_f1["Developer"] == developer_name]

    # Agrupar los datos por año de lanzamiento y contar la cantidad de juegos
    games_per_year = developer_data.groupby("Release_year")["Item_Id"].count()

    # Filtrar los juegos gratuitos del desarrollador y contar la cantidad por año
    free_games = developer_data[developer_data["Price"] == 0]
    free_games_per_year = free_games.groupby("Release_year")["Item_Id"].count()

    # Calcular el porcentaje de juegos gratuitos por año
    free_percentage_per_year = round((free_games_per_year / games_per_year) * 100, 2)

    # Calcular el total de juegos por año
    total_games_per_year = games_per_year.sum()

    # Crear una tabla con los resultados
    table = pd.concat([games_per_year, free_percentage_per_year], axis=1)
    table.columns = ["Cantidad de juegos", "Porcentaje de juegos gratuitos"]

    # Eliminar las filas con valores NaN
    table = table.dropna()

    # Agregar el signo de porcentaje a la columna "Porcentaje de juegos gratuitos"
    table["Porcentaje de juegos gratuitos"] = table["Porcentaje de juegos gratuitos"].apply(lambda x: f"{x}%" if not pd.isna(x) else x)

    table = table.reset_index()

    # Crear un diccionario con los resultados
    results = {"Tabla de resultados": table.to_dict(), "Total de juegos por año": total_games_per_year}

    return results

In [40]:
developer("Valve")

{1998: {'Total de juegos': 1, 'Porcentaje de juegos gratuitos': 'nan%'},
 1999: {'Total de juegos': 1, 'Porcentaje de juegos gratuitos': 'nan%'},
 2000: {'Total de juegos': 2, 'Porcentaje de juegos gratuitos': 'nan%'},
 2001: {'Total de juegos': 1, 'Porcentaje de juegos gratuitos': 'nan%'},
 2003: {'Total de juegos': 1, 'Porcentaje de juegos gratuitos': 'nan%'},
 2004: {'Total de juegos': 5, 'Porcentaje de juegos gratuitos': 'nan%'},
 2005: {'Total de juegos': 1, 'Porcentaje de juegos gratuitos': 'nan%'},
 2006: {'Total de juegos': 2, 'Porcentaje de juegos gratuitos': 'nan%'},
 2007: {'Total de juegos': 3, 'Porcentaje de juegos gratuitos': '33.33%'},
 2008: {'Total de juegos': 1, 'Porcentaje de juegos gratuitos': 'nan%'},
 2009: {'Total de juegos': 1, 'Porcentaje de juegos gratuitos': 'nan%'},
 2010: {'Total de juegos': 2, 'Porcentaje de juegos gratuitos': '50.0%'},
 2011: {'Total de juegos': 1, 'Porcentaje de juegos gratuitos': 'nan%'},
 2012: {'Total de juegos': 2, 'Porcentaje de juegos gratuitos': 'nan%'},
 2014: {'Total de juegos': 7, 'Porcentaje de juegos gratuitos': 'nan%'},
 2016: {'Total de juegos': 1, 'Porcentaje de juegos gratuitos': '100.0%'},
 2017: {'Total de juegos': 2, 'Porcentaje de juegos gratuitos': 'nan%'},
 'Developer': 'Valve'}

In [39]:
def developer(developer_name: str):
    # Filtrar los datos del DataFrame por el nombre del desarrollador
    developer_data = df_f1[df_f1["Developer"] == developer_name]

    # Agrupar los datos por año de lanzamiento y contar la cantidad de juegos
    games_per_year = developer_data.groupby("Release_year")["Item_Id"].count()

    # Filtrar los juegos gratuitos del desarrollador y contar la cantidad por año
    free_games = developer_data[developer_data["Price"] == 0]
    free_games_per_year = free_games.groupby("Release_year")["Item_Id"].count()

    # Calcular el porcentaje de juegos gratuitos por año
    free_percentage_per_year = round((free_games_per_year / games_per_year) * 100, 2)

    # Crear un diccionario con los resultados por año
    results = {}
    for year in games_per_year.index:
        year_results = {"Total de juegos": games_per_year[year], "Porcentaje de juegos gratuitos": f"{free_percentage_per_year[year]}%"}
        results[year] = year_results

    # Agregar el nombre del desarrollador al diccionario de resultados
    results["Developer"] = developer_name

    return results

In [50]:
def developer(developer_name: str):
    # Filtrar los datos del DataFrame por el nombre del desarrollador
    developer_data = df_f1[df_f1["Developer"] == developer_name]

    # Agrupar los datos por año de lanzamiento y contar la cantidad de juegos
    games_per_year = developer_data.groupby("Release_year")["Item_Id"].count()

    # Filtrar los juegos gratuitos del desarrollador y contar la cantidad por año
    free_games = developer_data[developer_data["Price"] == 0]
    free_games_per_year = free_games.groupby("Release_year")["Item_Id"].count()

    # Calcular el porcentaje de juegos gratuitos por año
    free_percentage_per_year = round((free_games_per_year / games_per_year) * 100, 2)

    # Crear un diccionario con los resultados por año
    results = {}
    for year in games_per_year.index:
        year_results = {"Total de juegos": games_per_year[year], "Porcentaje de juegos gratuitos": f"{free_percentage_per_year[year]}%"}
        if not pd.isna(free_percentage_per_year[year]):
            results[year] = year_results

    # Agregar el nombre del desarrollador al diccionario de resultados
    results["Developer"] = developer_name

    return results

In [51]:
developer("Valve")

{2007: {'Total de juegos': 3, 'Porcentaje de juegos gratuitos': '33.33%'},
 2010: {'Total de juegos': 2, 'Porcentaje de juegos gratuitos': '50.0%'},
 2016: {'Total de juegos': 1, 'Porcentaje de juegos gratuitos': '100.0%'},
 'Developer': 'Valve'}

In [43]:
df7 = pd.read_parquet('User_reviews.parquet')
df8 = pd.read_parquet('Output_Steam_Games.parquet')
df9 = pd.read_parquet('User_items.parquet')

In [56]:
df9

,User_Id,Items_Count,Item_Id,Item_Name,Playtime_Forever
0,76561197970982479,277,10.0,Counter-Strike,6.0
1,76561197970982479,277,20.0,Team Fortress Classic,0.0
2,76561197970982479,277,30.0,Day of Defeat,7.0
3,76561197970982479,277,40.0,Deathmatch Classic,0.0
4,76561197970982479,277,50.0,Half-Life: Opposing Force,0.0
...,...,...,...,...,...
5170010,76561198329548331,7,373330.0,All Is Dust,0.0
5170011,76561198329548331,7,388490.0,One Way To Die: Steam Edition,3.0
5170012,76561198329548331,7,521570.0,You Have 10 Seconds 2,4.0
5170013,76561198329548331,7,519140.0,Minds Eyes,3.0
5170014,edward_tremethick,0,NaN,None,NaN

In [45]:
df7["Item_Id"] = df7["Item_Id"].astype(int)
merged_df = pd.merge(df7, df8, on='Item_Id')

In [57]:
merged_df = pd.merge(df7, df8, on='Item_Id')

In [ ]:
    # Obtener el top 3 de desarrolladores con juegos más recomendados para el año dado
    top_desarrolladores = top_desarrolladores_recomendados(year)

    # Devolver el resultado
    return {"top_desarrolladore= 1" : top_desarrolladores[0], "top_desarrollador 2" : top_desarrolladores[1], "top_desarrollador 3" : top_desarrolladores[2]}

In [ ]:
df9["Item_Id"] = df9["Item_Id"].astype(int)

In [ ]:
df7["Item_Id"] = df7["Item_Id"].astype(int)

In [68]:
df7 = pd.read_csv('User_reviews.csv')
df8 = pd.read_csv('Output_Steam_Games.csv')
df9 = pd.read_csv('User_items.csv')
merged_df = pd.merge(df7, df8, on='Item_Id')
merged_df = merged_df.rename(columns={'año': 'year'})
merged_df5 = merged_df[['User_Id', 'Price','Recommend','Item_Id']]
merged_df10 = pd.merge(df8, df9, on='Item_Id')
df_nuevo = merged_df10.drop(columns=["Item_Id","App_name","Price","Developer","Items_Count","Item_Name"])
df_f1 = df8[["Item_Id", "Price","Developer","Release_year"]]
df_merged123 = pd.merge(df8, df7, on='Item_Id') 
df_limpio = df_merged123[['User_Id', 'Item_Id','Developer','Release_year','Sentiment Analysis']]

MemoryError: Unable to allocate 772. MiB for an array with shape (24, 4215819) and data type int64

In [65]:
# Cargar solo las columnas necesarias
df7 = pd.read_csv('User_reviews.csv', usecols=['User_Id', 'Item_Id'])
df8 = pd.read_csv('Output_Steam_Games.csv', usecols=['Item_Id', 'Price', 'Developer', 'Release_year'])
df9 = pd.read_csv('User_items.csv', usecols=['User_Id', 'Item_Id', 'Recommend'])

# Combinar los datos de manera más eficiente
merged_df = pd.merge(df7, df8, on='Item_Id')
merged_df5 = merged_df[['User_Id', 'Price', 'Recommend', 'Item_Id']]
merged_df10 = pd.merge(df8[['Item_Id', 'Developer', 'Release_year']], df9, on='Item_Id')
df_nuevo = merged_df10.drop(columns=['Item_Id'])
df_f1 = df8[['Item_Id', 'Price', 'Release_year', 'Developer']].astype({'Price': 'float32', 'Release_year': 'int16'})

# Agrupar los datos y ordenarlos de manera más eficiente
df_merged123 = pd.merge(df8, df7, on='Item_Id')
df_limpio = df_merged123[['User_Id', 'Item_Id', 'Developer', 'Release_year']].astype({'Release_year': 'int16'})
df_limpio = df_limpio.groupby(['User_Id', 'Item_Id', 'Developer', 'Release_year']).size().reset_index(name='count')
df_limpio = df_limpio.sort_values(['User_Id', 'count', 'Release_year'], ascending=[True, False, True])
df_limpio = df_limpio.reset_index(drop=True)

ValueError: Usecols do not match columns, columns expected but not found: ['Recommend']

In [61]:
merged_df

,User_Id,Item_Id,Recommend,Sentiment Analysis,año,Publisher,App_name,Price,Developer,Accounting,...,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing,Release_year
0,76561197970982479,1250,True,2,2011,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
1,death-hunter,1250,True,2,2015,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
2,DJKamBer,1250,True,0,2013,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
3,diego9031,1250,True,2,2015,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
4,76561198081962345,1250,True,2,2014,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41797,laislabonita75,367780,True,2,2015,Soloweb Studios,Aero's Quest,4.99,"Soloweb Studios,Ravens Eye Studio",0,...,0,0,0,0,0,0,0,0,0,2015
41798,evilindiegaming,367780,True,2,2015,Soloweb Studios,Aero's Quest,4.99,"Soloweb Studios,Ravens Eye Studio",0,...,0,0,0,0,0,0,0,0,0,2015
41799,laislabonita75,305920,False,0,2015,"ShaunJS, Digerati Distribution",Another Perspective,5.99,ShaunJS,0,...,0,0,0,0,0,0,0,0,0,2014
41800,Gamer0009,306040,True,2,2015,Antanas Marcelionis,The Howler,1.99,"Antanas Marcelionis,Renė Petrulienė",0,...,0,0,1,0,0,1,0,0,0,2016
41801,llDracuwulf,307130,True,2,2015,Legend Studio,Asteria,4.99,Legend Studio,0,...,0,0,0,0,0,0,0,0,0,2014

In [62]:
def top_desarrolladores_recomendados(year):
    # Cargar el DataFrame de juegos
    

    # Filtrar los juegos por año
    df_year = merged_df[merged_df['year'] == year]

    # Agrupar los juegos por desarrollador y contar el número de juegos recomendados
    df_count = df_year[df_year['Recommend'] == True][df_year['Sentiment Analysis'] == 2].groupby('Developer')['App_name'].count().reset_index()

    # Ordenar los resultados por número de juegos recomendados y devolver los tres primeros desarrolladores
    top_desarrolladores = df_count.sort_values('App_name', ascending=False).head(3)['Developer'].tolist()

    # Devolver el top 3 de desarrolladores
    return top_desarrolladores

In [63]:
top_desarrolladores_recomendados('Valve')

[]

In [54]:
def userdata(user_id):
    
    if type(user_id) == int:
        user_id = str(user_id)

    
    if not user_id in merged_df5['User_Id'].values or not user_id in df9['User_Id'].values:
        return f"El user_id {user_id} no existe en la base de datos u.u."

    user_data = merged_df5[merged_df5['User_Id'] == user_id]

    user_items = df9[df9['User_Id'] == user_id]

    # Calcular la cantidad de dinero gastado por el usuario
    dinero_gastado = user_data['Price'].sum()

    # Calcular el porcentaje de recomendación en base a reviews.recommend
    recomendacion = user_data['Recommend'].sum()
    porcentaje_recomendacion = recomendacion / len(user_data) * 100

    # Calcular la cantidad de items
    cantidad_de_items = user_items['Item_Id'].nunique()

    # Crear un diccionario con los resultados
    resultados = {
        'Cantidad de dinero gastado': dinero_gastado,
        'Porcentaje de recomendación': porcentaje_recomendacion,
        'Cantidad de items': cantidad_de_items
    }

    return resultados

In [55]:
userdata(76561197970982479	)

{'Cantidad de dinero gastado': 29.979999999999997,
 'Porcentaje de recomendación': 100.0,
 'Cantidad de items': 277}

In [6]:
import pandas as pd
df7 = pd.read_parquet('User_reviews.parquet')
df8 = pd.read_parquet('Output_steam_games.parquet')
df9 = pd.read_parquet('User_items.parquet')
merged_df = pd.merge(df7, df8, on='Item_Id')
merged_df = merged_df.rename(columns={'año': 'year'})
merged_df5 = merged_df[['User_Id', 'Price','Recommend','Item_Id']]
merged_df10 = pd.merge(df8, df9, on='Item_Id')
df_nuevo = merged_df10.drop(columns=['Item_Id','App_name','Price','Developer','Items_Count','Item_Name'])
df_f1 = df8[["Item_Id", "Price","Developer","Release_year"]]
df_merged123 = pd.merge(df8, df7, on='Item_Id') 
df_limpio = df_merged123[['User_Id', 'Item_Id','Developer','Release_year','Sentiment Analysis']]

In [5]:
merged_df

,User_Id,Item_Id,Recommend,Sentiment Analysis,year,Publisher,App_name,Price,Developer,Accounting,...,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing,Release_year
0,76561197970982479,1250,True,2,2011,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
1,death-hunter,1250,True,2,2015,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
2,DJKamBer,1250,True,0,2013,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
3,diego9031,1250,True,2,2015,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
4,76561198081962345,1250,True,2,2014,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41797,laislabonita75,367780,True,2,2015,Soloweb Studios,Aero's Quest,4.99,"Soloweb Studios,Ravens Eye Studio",0,...,0,0,0,0,0,0,0,0,0,2015
41798,evilindiegaming,367780,True,2,2015,Soloweb Studios,Aero's Quest,4.99,"Soloweb Studios,Ravens Eye Studio",0,...,0,0,0,0,0,0,0,0,0,2015
41799,laislabonita75,305920,False,0,2015,"ShaunJS, Digerati Distribution",Another Perspective,5.99,ShaunJS,0,...,0,0,0,0,0,0,0,0,0,2014
41800,Gamer0009,306040,True,2,2015,Antanas Marcelionis,The Howler,1.99,"Antanas Marcelionis,Renė Petrulienė",0,...,0,0,1,0,0,1,0,0,0,2016
41801,llDracuwulf,307130,True,2,2015,Legend Studio,Asteria,4.99,Legend Studio,0,...,0,0,0,0,0,0,0,0,0,2014

In [7]:
%load_ext memory_profiler

The memory_profiler extension is already loaded. To reload it, use:
  %reload_ext memory_profiler

In [8]:
from memory_profiler import profile

@profile
def top_desarrolladores_recomendados(year):
    # Cargar el DataFrame de juegos
    

    # Filtrar los juegos por año
    df_year = merged_df[merged_df['year'] == year]

    # Agrupar los juegos por desarrollador y contar el número de juegos recomendados
    df_count = df_year[df_year['Recommend'] == True][df_year['Sentiment Analysis'] == 2].groupby('Developer')['App_name'].count().reset_index()

    # Ordenar los resultados por número de juegos recomendados y devolver los tres primeros desarrolladores
    top_desarrolladores = df_count.sort_values('App_name', ascending=False).head(3)['Developer'].tolist()

    # Devolver el top 3 de desarrolladores
    return top_desarrolladores

In [31]:
def top_desarrolladores_recomendados(year):
    # Cargar el DataFrame de juegos utilizando read_parquet
    df = pd.read_parquet('archivo.parquet')

    # Filtrar los juegos por año utilizando la función query
    df_year = df.query('year == @year')

    # Convertir la columna year a un tipo de datos entero más pequeño
    df_year['year'] = df_year['year'].astype('int16')

    # Agrupar los juegos por desarrollador y contar el número de juegos recomendados utilizando query
    df_count = df_year.query('Recommend == True and `Sentiment Analysis` == 2').groupby('Developer', as_index=False)['App_name'].count()

    # Obtener los tres desarrolladores con el mayor número de juegos recomendados utilizando nlargest
    top_desarrolladores = df_count.nlargest(3, 'App_name', keep='all').reset_index(drop=True)['Developer'].tolist()

    # Devolver el top 3 de desarrolladores
    return top_desarrolladores

In [9]:
%memit top_desarrolladores_recomendados(2015)

In [ ]:
def top_desarrolladores_recomendados(year):
    # Cargar el DataFrame de juegos utilizando read_parquet
    df = pd.read_parquet('archivo.parquet')

    # Filtrar los juegos por año utilizando la función query
    df_year = df.query('year == @year')

    # Convertir la columna year a un tipo de datos entero más pequeño
    df_year['year'] = df_year['year'].astype('int16')

    # Agrupar los juegos por desarrollador y contar el número de juegos recomendados utilizando query
    df_count = df_year.query('Recommend == True and `Sentiment Analysis` == 2').groupby('Developer', as_index=False)['App_name'].count()

    # Obtener los tres desarrolladores con el mayor número de juegos recomendados utilizando nlargest
    top_desarrolladores = df_count.nlargest(3, 'App_name')['Developer'].tolist()

    # Devolver el top 3 de desarrolladores
    return top_desarrolladores

In [ ]:
def top_desarrolladores_recomendados(year):
    # Cargar el DataFrame de juegos utilizando read_parquet
    df = pd.read_parquet('archivo.parquet')

    # Filtrar los juegos por año utilizando la función query
    df_year = df.query('year == @year')

    # Convertir la columna year a un tipo de datos entero más pequeño
    df_year['year'] = df_year['year'].astype('int16')

    # Agrupar los juegos por desarrollador y contar el número de juegos recomendados utilizando query
    df_count = df_year.query('Recommend == True and `Sentiment Analysis` == 2').groupby('Developer', as_index=False)['App_name'].count()

    # Obtener los tres desarrolladores con el mayor número de juegos recomendados utilizando nlargest
    top_desarrolladores = df_count.nlargest(3, 'App_name')['Developer'].tolist()

    # Devolver el top 3 de desarrolladores
    return top_desarrolladores

In [ ]:
def top_desarrolladores_recomendados(year):
    # Cargar el DataFrame de juegos utilizando read_parquet
    df = pd.read_parquet('archivo.parquet')

    # Filtrar los juegos por año utilizando la función query
    df_year = df.query('year == @year')

    # Convertir la columna year a un tipo de datos entero más pequeño
    df_year['year'] = df_year['year'].astype('int16')

    # Agrupar los juegos por desarrollador y contar el número de juegos recomendados utilizando query
    df_count = df_year.query('Recommend == True and `Sentiment Analysis` == 2').groupby('Developer', as_index=False)['App_name'].count()

    # Obtener los tres desarrolladores con el mayor número de juegos recomendados utilizando nlargest
    top_desarrolladores = df_count.nlargest(3, 'App_name')['Developer'].tolist()

    # Devolver el top 3 de desarrolladores
    return top_desarrolladores

In [11]:
merged_df[merged_df['year'] == 2015]

,User_Id,Item_Id,Recommend,Sentiment Analysis,year,Publisher,App_name,Price,Developer,Accounting,...,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing,Release_year
1,death-hunter,1250,True,2,2015,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
3,diego9031,1250,True,2,2015,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
7,EndAtHallow,1250,True,0,2015,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
12,76561198038840599,1250,True,2,2015,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
13,76561198065247694,1250,True,2,2015,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41797,laislabonita75,367780,True,2,2015,Soloweb Studios,Aero's Quest,4.99,"Soloweb Studios,Ravens Eye Studio",0,...,0,0,0,0,0,0,0,0,0,2015
41798,evilindiegaming,367780,True,2,2015,Soloweb Studios,Aero's Quest,4.99,"Soloweb Studios,Ravens Eye Studio",0,...,0,0,0,0,0,0,0,0,0,2015
41799,laislabonita75,305920,False,0,2015,"ShaunJS, Digerati Distribution",Another Perspective,5.99,ShaunJS,0,...,0,0,0,0,0,0,0,0,0,2014
41800,Gamer0009,306040,True,2,2015,Antanas Marcelionis,The Howler,1.99,"Antanas Marcelionis,Renė Petrulienė",0,...,0,0,1,0,0,1,0,0,0,2016
41801,llDracuwulf,307130,True,2,2015,Legend Studio,Asteria,4.99,Legend Studio,0,...,0,0,0,0,0,0,0,0,0,2014

In [19]:
import gzip
import pandas as pd
import os

# Leer el archivo Parquet
df66 = pd.read_parquet('User_items.parquet')

# Escribir el archivo Parquet en un archivo temporal
temp_file = 'temp.parquet'
df66.to_parquet(temp_file)

# Comprimir el archivo temporal con gzip
with open(temp_file, 'rb') as f_in:
    with gzip.open('archivo.parquet.gz', 'wb') as f_out:
        f_out.writelines(f_in)

# Eliminar el archivo temporal
os.remove(temp_file)

In [3]:
%load_ext memory_profiler

In [ ]:
df78 = pd.read_parquet('User_items.parquet')

In [31]:
def top_desarrolladores_recomendados(year):
    # Cargar el DataFrame de juegos
    

    # Filtrar los juegos por año
    df_year = merged_df[merged_df['year'] == year]

    # Agrupar los juegos por desarrollador y contar el número de juegos recomendados
    df_count = df_year[df_year['Recommend'] == True][df_year['Sentiment Analysis'] == 2].groupby('Developer')['App_name'].count().reset_index()

    # Ordenar los resultados por número de juegos recomendados y devolver los tres primeros desarrolladores
    top_desarrolladores = df_count.sort_values('App_name', ascending=False).head(3)['Developer'].tolist()
    del df_year, df_count
    # Devolver el top 3 de desarrolladores
    return top_desarrolladores

In [29]:
%load_ext memory_profiler

The memory_profiler extension is already loaded. To reload it, use:
  %reload_ext memory_profiler

In [32]:
%memit top_desarrolladores_recomendados(2011)

peak memory: 144.85 MiB, increment: 0.03 MiB

In [30]:
%memit top_desarrolladores_recomendados(2011)

peak memory: 144.74 MiB, increment: 0.14 MiB

In [34]:
def top_desarrolladores_recomendados(year):
    # Cargar el DataFrame de juegos
    df = pd.read_parquet('Prueba11.parquet')

    # Filtrar los juegos por año
    df_year = df.query('year == @year')

    # Agrupar los juegos por desarrollador y contar el número de juegos recomendados
    df_count = df_year.query('Recommend == True and `Sentiment Analysis` == 2').groupby('Developer', as_index=False)['App_name'].count()

    # Ordenar los resultados por número de juegos recomendados y devolver los tres primeros desarrolladores
    top_desarrolladores = df_count.nlargest(3, 'App_name')['Developer'].tolist()

    # Devolver el top 3 de desarrolladores
    return top_desarrolladores

In [35]:
%memit top_desarrolladores_recomendados(2011)

peak memory: 176.91 MiB, increment: 18.03 MiB

In [18]:
%memit top_desarrolladores_recomendados(2011)

peak memory: 300.05 MiB, increment: 5.73 MiB

In [ ]:
import pandas as pd
df7 = pd.read_parquet('User_reviews.parquet')
df8 = pd.read_parquet('Output_steam_games.parquet')
df9 = pd.read_parquet('User_items.parquet')
merged_df = pd.merge(df7, df8, on='Item_Id')
merged_df = merged_df.rename(columns={'año': 'year'})
merged_df5 = merged_df[['User_Id', 'Price','Recommend','Item_Id']]
merged_df10 = pd.merge(df8, df9, on='Item_Id')
df_nuevo = merged_df10.drop(columns=['Item_Id','App_name','Price','Developer','Items_Count','Item_Name'])
df_f1 = df8[["Item_Id", "Price","Developer","Release_year"]]
df_merged123 = pd.merge(df8, df7, on='Item_Id') 
df_limpio = df_merged123[['User_Id', 'Item_Id','Developer','Release_year','Sentiment Analysis']]

In [39]:
import pandas as pd
df7 = pd.read_parquet('User_reviews.parquet')
df8 = pd.read_parquet('Output_steam_games.parquet')
df9 = pd.read_parquet('User_items.parquet')

In [40]:
merged_df = pd.merge(df7, df8, on='Item_Id')
merged_df = merged_df.rename(columns={'año': 'year'})

In [41]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41802 entries, 0 to 41801
Data columns (total 32 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   User_Id                    41802 non-null  object
 1   Item_Id                    41802 non-null  int64
 2   Recommend                  41802 non-null  bool
 3   Sentiment Analysis         41802 non-null  int64
 4   year                       41802 non-null  int64
 5   Publisher                  41159 non-null  object
 6   App_name                   41802 non-null  object
 7   Price                      41222 non-null  float64
 8   Developer                  41555 non-null  object
 9   Accounting                 41802 non-null  int64
 10  Action                     41802 non-null  int64
 11  Adventure                  41802 non-null  int64
 12  Animation &amp; Modeling   41802 non-null  int64
 13  Audio Production           41802 non-null  int64
 14  Casual                     41802 non-null  int64
 15  Design &amp; Illustration  41802 non-null  int64
 16  Early Access               41802 non-null  int64
 17  Education                  41802 non-null  int64
 18  Free to Play               41802 non-null  int64
 19  Indie                      41802 non-null  int64
 20  Massively Multiplayer      41802 non-null  int64
 21  Photo Editing              41802 non-null  int64
 22  RPG                        41802 non-null  int64
 23  Racing                     41802 non-null  int64
 24  Simulation                 41802 non-null  int64
 25  Software Training          41802 non-null  int64
 26  Sports                     41802 non-null  int64
 27  Strategy                   41802 non-null  int64
 28  Utilities                  41802 non-null  int64
 29  Video Production           41802 non-null  int64
 30  Web Publishing             41802 non-null  int64
 31  Release_year               41802 non-null  int64
dtypes: bool(1), float64(1), int64(26), object(4)
memory usage: 9.9+ MB

In [49]:
int64_cols = df8.select_dtypes(include=['int64']).columns.tolist()

In [50]:
df8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29966 entries, 0 to 29965
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Publisher                  23949 non-null  object
 1   App_name                   29965 non-null  object
 2   Price                      28817 non-null  float64
 3   Item_Id                    29966 non-null  int64
 4   Developer                  28716 non-null  object
 5   Accounting                 29966 non-null  int64
 6   Action                     29966 non-null  int64
 7   Adventure                  29966 non-null  int64
 8   Animation &amp; Modeling   29966 non-null  int64
 9   Audio Production           29966 non-null  int64
 10  Casual                     29966 non-null  int64
 11  Design &amp; Illustration  29966 non-null  int64
 12  Early Access               29966 non-null  int64
 13  Education                  29966 non-null  int64
 14  Free to Play               29966 non-null  int64
 15  Indie                      29966 non-null  int64
 16  Massively Multiplayer      29966 non-null  int64
 17  Photo Editing              29966 non-null  int64
 18  RPG                        29966 non-null  int64
 19  Racing                     29966 non-null  int64
 20  Simulation                 29966 non-null  int64
 21  Software Training          29966 non-null  int64
 22  Sports                     29966 non-null  int64
 23  Strategy                   29966 non-null  int64
 24  Utilities                  29966 non-null  int64
 25  Video Production           29966 non-null  int64
 26  Web Publishing             29966 non-null  int64
 27  Release_year               29966 non-null  int64
dtypes: float64(1), int64(24), object(3)
memory usage: 6.4+ MB

In [58]:
df8[int64_cols] = df8[int64_cols].astype('int64')

In [55]:
df8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29966 entries, 0 to 29965
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Publisher                  23949 non-null  object
 1   App_name                   29965 non-null  object
 2   Price                      28817 non-null  float64
 3   Item_Id                    29966 non-null  int32
 4   Developer                  28716 non-null  object
 5   Accounting                 29966 non-null  int32
 6   Action                     29966 non-null  int32
 7   Adventure                  29966 non-null  int32
 8   Animation &amp; Modeling   29966 non-null  int32
 9   Audio Production           29966 non-null  int32
 10  Casual                     29966 non-null  int32
 11  Design &amp; Illustration  29966 non-null  int32
 12  Early Access               29966 non-null  int32
 13  Education                  29966 non-null  int32
 14  Free to Play               29966 non-null  int32
 15  Indie                      29966 non-null  int32
 16  Massively Multiplayer      29966 non-null  int32
 17  Photo Editing              29966 non-null  int32
 18  RPG                        29966 non-null  int32
 19  Racing                     29966 non-null  int32
 20  Simulation                 29966 non-null  int32
 21  Software Training          29966 non-null  int32
 22  Sports                     29966 non-null  int32
 23  Strategy                   29966 non-null  int32
 24  Utilities                  29966 non-null  int32
 25  Video Production           29966 non-null  int32
 26  Web Publishing             29966 non-null  int32
 27  Release_year               29966 non-null  int32
dtypes: float64(1), int32(24), object(3)
memory usage: 3.7+ MB

In [59]:
df8

,Publisher,App_name,Price,Item_Id,Developer,Accounting,Action,Adventure,Animation &amp; Modeling,Audio Production,...,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing,Release_year
0,Kotoshiro,Lost Summoner Kitty,4.99,-25292,Kotoshiro,0,1,0,0,0,...,0,0,1,0,0,1,0,0,0,2018
1,"Making Fun, Inc.",Ironbound,0.00,-11380,Secret Level SRL,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,2018
2,Poolians.com,Real Pool 3D - Poolians,0.00,14930,Poolians.com,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,2017
3,彼岸领域,弹炸人2222,0.99,-19032,彼岸领域,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,2017
4,Trickjump Games Ltd,Battle Royale Trainer,3.99,-13892,Trickjump Games Ltd,0,1,1,0,0,...,0,0,1,0,0,0,0,0,0,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29961,Bidoniera Games,Kebab it Up!,1.99,24504,Bidoniera Games,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,2018
29962,Ghost_RUS Games,Colony On Mars,1.99,-12792,"Nikita ""Ghost_RUS""",0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,2018
29963,Sacada,LOGistICAL: South Africa,4.99,12634,Sacada,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,2018
29964,Laush Studio,Russian Roads,1.99,20836,Laush Dmitriy Sergeevich,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,2018
29965,SIXNAILS,EXIT 2 - Directions,4.99,3510,"xropi,stev3ns",0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2017

In [48]:
merged_df.to_parquet('Top 3 Desarrolladores.parquet')

In [46]:
merged_df

,User_Id,Item_Id,Recommend,Sentiment Analysis,year,Publisher,App_name,Price,Developer,Accounting,...,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing,Release_year
0,76561197970982479,1250,True,2,2011,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
1,death-hunter,1250,True,2,2015,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
2,DJKamBer,1250,True,0,2013,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
3,diego9031,1250,True,2,2015,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
4,76561198081962345,1250,True,2,2014,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41797,laislabonita75,-25436,True,2,2015,Soloweb Studios,Aero's Quest,4.99,"Soloweb Studios,Ravens Eye Studio",0,...,0,0,0,0,0,0,0,0,0,2015
41798,evilindiegaming,-25436,True,2,2015,Soloweb Studios,Aero's Quest,4.99,"Soloweb Studios,Ravens Eye Studio",0,...,0,0,0,0,0,0,0,0,0,2015
41799,laislabonita75,-21760,False,0,2015,"ShaunJS, Digerati Distribution",Another Perspective,5.99,ShaunJS,0,...,0,0,0,0,0,0,0,0,0,2014
41800,Gamer0009,-21640,True,2,2015,Antanas Marcelionis,The Howler,1.99,"Antanas Marcelionis,Renė Petrulienė",0,...,0,0,1,0,0,1,0,0,0,2016
41801,llDracuwulf,-20550,True,2,2015,Legend Studio,Asteria,4.99,Legend Studio,0,...,0,0,0,0,0,0,0,0,0,2014

In [47]:
merged_df

,User_Id,Item_Id,Recommend,Sentiment Analysis,year,Publisher,App_name,Price,Developer,Accounting,...,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing,Release_year
0,76561197970982479,1250,True,2,2011,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
1,death-hunter,1250,True,2,2015,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
2,DJKamBer,1250,True,0,2013,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
3,diego9031,1250,True,2,2015,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
4,76561198081962345,1250,True,2,2014,Tripwire Interactive,Killing Floor,19.99,Tripwire Interactive,0,...,0,0,0,0,0,0,0,0,0,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41797,laislabonita75,-25436,True,2,2015,Soloweb Studios,Aero's Quest,4.99,"Soloweb Studios,Ravens Eye Studio",0,...,0,0,0,0,0,0,0,0,0,2015
41798,evilindiegaming,-25436,True,2,2015,Soloweb Studios,Aero's Quest,4.99,"Soloweb Studios,Ravens Eye Studio",0,...,0,0,0,0,0,0,0,0,0,2015
41799,laislabonita75,-21760,False,0,2015,"ShaunJS, Digerati Distribution",Another Perspective,5.99,ShaunJS,0,...,0,0,0,0,0,0,0,0,0,2014
41800,Gamer0009,-21640,True,2,2015,Antanas Marcelionis,The Howler,1.99,"Antanas Marcelionis,Renė Petrulienė",0,...,0,0,1,0,0,1,0,0,0,2016
41801,llDracuwulf,-20550,True,2,2015,Legend Studio,Asteria,4.99,Legend Studio,0,...,0,0,0,0,0,0,0,0,0,2014

In [7]:
merged_df5 = merged_df[['User_Id', 'Price','Recommend','Item_Id']]

In [10]:
merged_df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41802 entries, 0 to 41801
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   User_Id    41802 non-null  object
 1   Price      41222 non-null  float64
 2   Recommend  41802 non-null  bool
 3   Item_Id    41802 non-null  int8
dtypes: bool(1), float64(1), int8(1), object(1)
memory usage: 734.9+ KB

In [31]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49186 entries, 0 to 49185
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   User_Id             49186 non-null  object
 1   Item_Id             49186 non-null  int64
 2   Recommend           49186 non-null  bool
 3   Sentiment Analysis  49186 non-null  int64
 4   año                 49186 non-null  int64
dtypes: bool(1), int64(3), object(1)
memory usage: 1.5+ MB

In [9]:
int64_cols = merged_df5.select_dtypes(include=['int64']).columns.tolist()

In [11]:
df9.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5170015 entries, 0 to 5170014
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   User_Id           object
 1   Items_Count       int64
 2   Item_Id           float64
 3   Item_Name         object
 4   Playtime_Forever  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 197.2+ MB

In [32]:
int64_cols = df7.select_dtypes(include=['int64']).columns.tolist()

In [33]:
df7[int64_cols] = df7[int64_cols].astype('int8')

In [34]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49186 entries, 0 to 49185
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   User_Id             49186 non-null  object
 1   Item_Id             49186 non-null  int8
 2   Recommend           49186 non-null  bool
 3   Sentiment Analysis  49186 non-null  int8
 4   año                 49186 non-null  int8
dtypes: bool(1), int8(3), object(1)
memory usage: 576.5+ KB

In [14]:
df9.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5170015 entries, 0 to 5170014
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   User_Id           object
 1   Items_Count       int8
 2   Item_Id           float64
 3   Item_Name         object
 4   Playtime_Forever  float64
dtypes: float64(2), int8(1), object(2)
memory usage: 162.7+ MB

In [27]:
float64_cols = df8.select_dtypes(include=['float64']).columns.tolist()

In [28]:
df8[float64_cols] = df8[float64_cols].astype('float32')

In [29]:
df8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29966 entries, 0 to 29965
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Publisher                  23949 non-null  object
 1   App_name                   29965 non-null  object
 2   Price                      28817 non-null  float32
 3   Item_Id                    29966 non-null  int8
 4   Developer                  28716 non-null  object
 5   Accounting                 29966 non-null  int8
 6   Action                     29966 non-null  int8
 7   Adventure                  29966 non-null  int8
 8   Animation &amp; Modeling   29966 non-null  int8
 9   Audio Production           29966 non-null  int8
 10  Casual                     29966 non-null  int8
 11  Design &amp; Illustration  29966 non-null  int8
 12  Early Access               29966 non-null  int8
 13  Education                  29966 non-null  int8
 14  Free to Play               29966 non-null  int8
 15  Indie                      29966 non-null  int8
 16  Massively Multiplayer      29966 non-null  int8
 17  Photo Editing              29966 non-null  int8
 18  RPG                        29966 non-null  int8
 19  Racing                     29966 non-null  int8
 20  Simulation                 29966 non-null  int8
 21  Software Training          29966 non-null  int8
 22  Sports                     29966 non-null  int8
 23  Strategy                   29966 non-null  int8
 24  Utilities                  29966 non-null  int8
 25  Video Production           29966 non-null  int8
 26  Web Publishing             29966 non-null  int8
 27  Release_year               29966 non-null  int8
dtypes: float32(1), int8(24), object(3)
memory usage: 1.5+ MB

In [35]:
df7.to_parquet('User_reviews_reducido.parquet')

In [8]:
merged_df5.to_parquet('User_Data.parquet')

In [8]:
float64_cols = merged_df.select_dtypes(include=['float64']).columns.tolist()

# Convertir las columnas de tipo float64 a float8

In [9]:
merged_df[float64_cols] = merged_df[float64_cols].astype('float16')

In [36]:
df7

                 User_Id  Item_Id  Recommend  Sentiment Analysis  año
0      76561197970982479      -30       True                   2  -37
1      76561197970982479      -72       True                   2  -37
2      76561197970982479      102       True                   2  -37
3                js41637      -38       True                   2  -34
4                js41637      -28       True                   2  -35
...                  ...      ...        ...                 ...  ...
49181            wayfeng      -38       True                   1  -33
49182  76561198251004808       28       True                   2  -33
49183        72947282842      -38       True                   0  -33
49184          ApxLGhost      -38       True                   2  -33
49185  76561198267374962       48       True                   2  -33

[49186 rows x 5 columns]

In [10]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41802 entries, 0 to 41801
Data columns (total 32 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   User_Id                    41802 non-null  object
 1   Item_Id                    41802 non-null  int8
 2   Recommend                  41802 non-null  bool
 3   Sentiment Analysis         41802 non-null  int8
 4   year                       41802 non-null  int8
 5   Publisher                  41159 non-null  object
 6   App_name                   41802 non-null  object
 7   Price                      41222 non-null  float16
 8   Developer                  41555 non-null  object
 9   Accounting                 41802 non-null  int8
 10  Action                     41802 non-null  int8
 11  Adventure                  41802 non-null  int8
 12  Animation &amp; Modeling   41802 non-null  int8
 13  Audio Production           41802 non-null  int8
 14  Casual                     41802 non-null  int8
 15  Design &amp; Illustration  41802 non-null  int8
 16  Early Access               41802 non-null  int8
 17  Education                  41802 non-null  int8
 18  Free to Play               41802 non-null  int8
 19  Indie                      41802 non-null  int8
 20  Massively Multiplayer      41802 non-null  int8
 21  Photo Editing              41802 non-null  int8
 22  RPG                        41802 non-null  int8
 23  Racing                     41802 non-null  int8
 24  Simulation                 41802 non-null  int8
 25  Software Training          41802 non-null  int8
 26  Sports                     41802 non-null  int8
 27  Strategy                   41802 non-null  int8
 28  Utilities                  41802 non-null  int8
 29  Video Production           41802 non-null  int8
 30  Web Publishing             41802 non-null  int8
 31  Release_year               41802 non-null  int8
dtypes: bool(1), float16(1), int8(26), object(4)
memory usage: 2.4+ MB

In [19]:
merged_df.to_parquet('Top 3 Desarroladores.parquet')

In [4]:
df_year = merged_df[merged_df['year'] == year]

NameError: name 'year' is not defined

In [15]:
merged_df10 = pd.merge(df8, df9, on='Item_Id')
df_nuevo = merged_df10.drop(columns=['Item_Id','App_name','Price','Developer','Items_Count','Item_Name'])

In [16]:
int64_cols = df_nuevo.select_dtypes(include=['int64']).columns.tolist()
int64_cols

['Accounting',
 'Action',
 'Adventure',
 'Animation &amp; Modeling',
 'Audio Production',
 'Casual',
 'Design &amp; Illustration',
 'Early Access',
 'Education',
 'Free to Play',
 'Indie',
 'Massively Multiplayer',
 'Photo Editing',
 'RPG',
 'Racing',
 'Simulation',
 'Software Training',
 'Sports',
 'Strategy',
 'Utilities',
 'Video Production',
 'Web Publishing',
 'Release_year']

In [17]:
df_nuevo[int64_cols] = df_nuevo[int64_cols].astype('int8')

In [18]:
df_nuevo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4215819 entries, 0 to 4215818
Data columns (total 26 columns):
 #   Column                     Dtype
---  ------                     -----
 0   Publisher                  object
 1   Accounting                 int8
 2   Action                     int8
 3   Adventure                  int8
 4   Animation &amp; Modeling   int8
 5   Audio Production           int8
 6   Casual                     int8
 7   Design &amp; Illustration  int8
 8   Early Access               int8
 9   Education                  int8
 10  Free to Play               int8
 11  Indie                      int8
 12  Massively Multiplayer      int8
 13  Photo Editing              int8
 14  RPG                        int8
 15  Racing                     int8
 16  Simulation                 int8
 17  Software Training          int8
 18  Sports                     int8
 19  Strategy                   int8
 20  Utilities                  int8
 21  Video Production           int8
 22  Web Publishing             int8
 23  Release_year               int8
 24  User_Id                    object
 25  Playtime_Forever           float64
dtypes: float64(1), int8(23), object(2)
memory usage: 189.0+ MB

In [20]:
float64_cols = df_nuevo.select_dtypes(include=['float64']).columns.tolist()

In [21]:
df_nuevo[float64_cols] = df_nuevo[float64_cols].astype('float16')

c:\Python311\Lib\site-packages\pandas\core\dtypes\astype.py:134: RuntimeWarning: overflow encountered in cast
  return arr.astype(dtype, copy=True)

In [22]:
df_nuevo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4215819 entries, 0 to 4215818
Data columns (total 26 columns):
 #   Column                     Dtype
---  ------                     -----
 0   Publisher                  object
 1   Accounting                 int8
 2   Action                     int8
 3   Adventure                  int8
 4   Animation &amp; Modeling   int8
 5   Audio Production           int8
 6   Casual                     int8
 7   Design &amp; Illustration  int8
 8   Early Access               int8
 9   Education                  int8
 10  Free to Play               int8
 11  Indie                      int8
 12  Massively Multiplayer      int8
 13  Photo Editing              int8
 14  RPG                        int8
 15  Racing                     int8
 16  Simulation                 int8
 17  Software Training          int8
 18  Sports                     int8
 19  Strategy                   int8
 20  Utilities                  int8
 21  Video Production           int8
 22  Web Publishing             int8
 23  Release_year               int8
 24  User_Id                    object
 25  Playtime_Forever           float16
dtypes: float16(1), int8(23), object(2)
memory usage: 164.8+ MB

In [37]:
df_nuevo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4215819 entries, 0 to 4215818
Data columns (total 26 columns):
 #   Column                     Dtype
---  ------                     -----
 0   Publisher                  object
 1   Accounting                 int64
 2   Action                     int64
 3   Adventure                  int64
 4   Animation &amp; Modeling   int64
 5   Audio Production           int64
 6   Casual                     int64
 7   Design &amp; Illustration  int64
 8   Early Access               int64
 9   Education                  int64
 10  Free to Play               int64
 11  Indie                      int64
 12  Massively Multiplayer      int64
 13  Photo Editing              int64
 14  RPG                        int64
 15  Racing                     int64
 16  Simulation                 int64
 17  Software Training          int64
 18  Sports                     int64
 19  Strategy                   int64
 20  Utilities                  int64
 21  Video Production           int64
 22  Web Publishing             int64
 23  Release_year               int64
 24  User_Id                    object
 25  Playtime_Forever           float64
dtypes: float64(1), int64(23), object(2)
memory usage: 836.3+ MB

In [1]:
df_nuevo.info()

NameError: name 'df_nuevo' is not defined

In [23]:
def UserForGenre(genero):
    if not genero in df_nuevo.columns:
        return f"El género {genero} no existe en la base de datos."
    
    df_genre = df_nuevo[df_nuevo[genero] == 1]

    usur_mas_horas = df_genre.groupby("User_Id")["Playtime_Forever"].sum().idxmax()

    filtro_usur = df_genre[df_genre["User_Id"] == usur_mas_horas]

    horas_jugXaño = filtro_usur.groupby("Release_year")["Playtime_Forever"].sum()

    registro = horas_jugXaño.to_dict()

    Horas_por_año = {}
    for clave, valor in registro.items():
        clave_formateada = f'Año: {int(clave)}'
        valor_formateado = int(valor)
        Horas_por_año[clave_formateada] = valor_formateado
    return {"Usuario con más horas jugadas": usur_mas_horas, "Horas jugadas por año": Horas_por_año}

In [3]:
%load_ext memory_profiler

In [24]:
%memit UserForGenre("Action")

In [44]:
%memit UserForGenre("Action")

peak memory: 487.26 MiB, increment: 303.36 MiB

In [38]:
df8

,Publisher,App_name,Price,Item_Id,Developer,Accounting,Action,Adventure,Animation &amp; Modeling,Audio Production,...,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing,Release_year
0,Kotoshiro,Lost Summoner Kitty,4.99,52,Kotoshiro,0,1,0,0,0,...,0,0,1,0,0,1,0,0,0,-30
1,"Making Fun, Inc.",Ironbound,0.00,-116,Secret Level SRL,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,-30
2,Poolians.com,Real Pool 3D - Poolians,0.00,82,Poolians.com,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,-31
3,彼岸领域,弹炸人2222,0.99,-88,彼岸领域,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,-31
4,Trickjump Games Ltd,Battle Royale Trainer,3.99,-68,Trickjump Games Ltd,0,1,1,0,0,...,0,0,1,0,0,0,0,0,0,-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29961,Bidoniera Games,Kebab it Up!,1.99,-72,Bidoniera Games,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,-30
29962,Ghost_RUS Games,Colony On Mars,1.99,8,"Nikita ""Ghost_RUS""",0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,-30
29963,Sacada,LOGistICAL: South Africa,4.99,90,Sacada,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,-30
29964,Laush Studio,Russian Roads,1.99,100,Laush Dmitriy Sergeevich,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,-30
29965,SIXNAILS,EXIT 2 - Directions,4.99,-74,"xropi,stev3ns",0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-31

In [37]:
df7

                 User_Id  Item_Id  Recommend  Sentiment Analysis  año
0      76561197970982479      -30       True                   2  -37
1      76561197970982479      -72       True                   2  -37
2      76561197970982479      102       True                   2  -37
3                js41637      -38       True                   2  -34
4                js41637      -28       True                   2  -35
...                  ...      ...        ...                 ...  ...
49181            wayfeng      -38       True                   1  -33
49182  76561198251004808       28       True                   2  -33
49183        72947282842      -38       True                   0  -33
49184          ApxLGhost      -38       True                   2  -33
49185  76561198267374962       48       True                   2  -33

[49186 rows x 5 columns]

In [60]:
df99 = pd.read_parquet('Output_steam_games.parquet')

In [61]:
df99

,Publisher,App_name,Price,Item_Id,Developer,Accounting,Action,Adventure,Animation &amp; Modeling,Audio Production,...,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing,Release_year
0,Kotoshiro,Lost Summoner Kitty,4.99,761140,Kotoshiro,0,1,0,0,0,...,0,0,1,0,0,1,0,0,0,2018
1,"Making Fun, Inc.",Ironbound,0.00,643980,Secret Level SRL,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,2018
2,Poolians.com,Real Pool 3D - Poolians,0.00,670290,Poolians.com,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,2017
3,彼岸领域,弹炸人2222,0.99,767400,彼岸领域,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,2017
4,Trickjump Games Ltd,Battle Royale Trainer,3.99,772540,Trickjump Games Ltd,0,1,1,0,0,...,0,0,1,0,0,0,0,0,0,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29961,Bidoniera Games,Kebab it Up!,1.99,745400,Bidoniera Games,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,2018
29962,Ghost_RUS Games,Colony On Mars,1.99,773640,"Nikita ""Ghost_RUS""",0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,2018
29963,Sacada,LOGistICAL: South Africa,4.99,733530,Sacada,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,2018
29964,Laush Studio,Russian Roads,1.99,610660,Laush Dmitriy Sergeevich,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,2018
29965,SIXNAILS,EXIT 2 - Directions,4.99,658870,"xropi,stev3ns",0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2017

In [65]:
df99.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29966 entries, 0 to 29965
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Publisher                  23949 non-null  object
 1   App_name                   29965 non-null  object
 2   Price                      28817 non-null  float64
 3   Item_Id                    29966 non-null  int64
 4   Developer                  28716 non-null  object
 5   Accounting                 29966 non-null  int64
 6   Action                     29966 non-null  int64
 7   Adventure                  29966 non-null  int64
 8   Animation &amp; Modeling   29966 non-null  int64
 9   Audio Production           29966 non-null  int64
 10  Casual                     29966 non-null  int64
 11  Design &amp; Illustration  29966 non-null  int64
 12  Early Access               29966 non-null  int64
 13  Education                  29966 non-null  int64
 14  Free to Play               29966 non-null  int64
 15  Indie                      29966 non-null  int64
 16  Massively Multiplayer      29966 non-null  int64
 17  Photo Editing              29966 non-null  int64
 18  RPG                        29966 non-null  int64
 19  Racing                     29966 non-null  int64
 20  Simulation                 29966 non-null  int64
 21  Software Training          29966 non-null  int64
 22  Sports                     29966 non-null  int64
 23  Strategy                   29966 non-null  int64
 24  Utilities                  29966 non-null  int64
 25  Video Production           29966 non-null  int64
 26  Web Publishing             29966 non-null  int64
 27  Release_year               29966 non-null  int64
dtypes: float64(1), int64(24), object(3)
memory usage: 6.4+ MB

In [62]:
df77 = pd.read_parquet('User_reviews.parquet')

In [63]:
df77

                 User_Id  Item_Id  Recommend  Sentiment Analysis   año
0      76561197970982479     1250       True                   2  2011
1      76561197970982479    22200       True                   2  2011
2      76561197970982479    43110       True                   2  2011
3                js41637   251610       True                   2  2014
4                js41637   227300       True                   2  2013
...                  ...      ...        ...                 ...   ...
49181            wayfeng      730       True                   1  2015
49182  76561198251004808   253980       True                   2  2015
49183        72947282842      730       True                   0  2015
49184          ApxLGhost      730       True                   2  2015
49185  76561198267374962   369200       True                   2  2015

[49186 rows x 5 columns]

In [64]:
df77.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49186 entries, 0 to 49185
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   User_Id             49186 non-null  object
 1   Item_Id             49186 non-null  int64
 2   Recommend           49186 non-null  bool
 3   Sentiment Analysis  49186 non-null  int64
 4   año                 49186 non-null  int64
dtypes: bool(1), int64(3), object(1)
memory usage: 1.5+ MB

In [66]:
df88 = pd.read_parquet('User_items.parquet')

In [67]:
df88

,User_Id,Items_Count,Item_Id,Item_Name,Playtime_Forever
0,76561197970982479,277,10.0,Counter-Strike,6.0
1,76561197970982479,277,20.0,Team Fortress Classic,0.0
2,76561197970982479,277,30.0,Day of Defeat,7.0
3,76561197970982479,277,40.0,Deathmatch Classic,0.0
4,76561197970982479,277,50.0,Half-Life: Opposing Force,0.0
...,...,...,...,...,...
5170010,76561198329548331,7,373330.0,All Is Dust,0.0
5170011,76561198329548331,7,388490.0,One Way To Die: Steam Edition,3.0
5170012,76561198329548331,7,521570.0,You Have 10 Seconds 2,4.0
5170013,76561198329548331,7,519140.0,Minds Eyes,3.0
5170014,edward_tremethick,0,NaN,None,NaN

In [68]:
df88.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5170015 entries, 0 to 5170014
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   User_Id           object
 1   Items_Count       int64
 2   Item_Id           float64
 3   Item_Name         object
 4   Playtime_Forever  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 197.2+ MB

In [69]:
int64_cols = df88.select_dtypes(include=['int64']).columns.tolist()

In [70]:
df88[int64_cols] = df88[int64_cols].astype('int32')

In [71]:
df88.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5170015 entries, 0 to 5170014
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   User_Id           object
 1   Items_Count       int32
 2   Item_Id           float64
 3   Item_Name         object
 4   Playtime_Forever  float64
dtypes: float64(2), int32(1), object(2)
memory usage: 177.5+ MB

In [72]:
df88

,User_Id,Items_Count,Item_Id,Item_Name,Playtime_Forever
0,76561197970982479,277,10.0,Counter-Strike,6.0
1,76561197970982479,277,20.0,Team Fortress Classic,0.0
2,76561197970982479,277,30.0,Day of Defeat,7.0
3,76561197970982479,277,40.0,Deathmatch Classic,0.0
4,76561197970982479,277,50.0,Half-Life: Opposing Force,0.0
...,...,...,...,...,...
5170010,76561198329548331,7,373330.0,All Is Dust,0.0
5170011,76561198329548331,7,388490.0,One Way To Die: Steam Edition,3.0
5170012,76561198329548331,7,521570.0,You Have 10 Seconds 2,4.0
5170013,76561198329548331,7,519140.0,Minds Eyes,3.0
5170014,edward_tremethick,0,NaN,None,NaN

In [73]:
df88.to_parquet('User_items_reducido_32.parquet')

In [74]:
df77.to_parquet('User_reviews_reducido_32.parquet')

In [75]:
df99.to_parquet('Output_steam_games_reducido_32.parquet')

In [85]:
import gzip
import shutil

with open('User_reviews_reducido.parquet', 'rb') as f_in:
    with gzip.open('User_reviews_reducido.parquet.gz', 'wb') as f_out:
        shutil.copyfileobj(f_in, f_out)

In [86]:
import os

size = os.path.getsize('User_reviews_reducido.parquet.gz')

print(f"El tamaño del archivo comprimido es de {size / 1024**2:.2f} MB")

El tamaño del archivo comprimido es de 0.35 MB

In [97]:
import gzip
import shutil

with open('User_items_reducido_32.parquet', 'rb') as f_in:
    with gzip.open('User_items_reducido_32.parquet.gz', 'wb') as f_out:
        shutil.copyfileobj(f_in, f_out)

In [98]:
import gzip
import pandas as pd

with gzip.open('User_items_reducido_32.parquet.gz', 'rb') as f:
    df632 = pd.read_parquet(f, engine='pyarrow')

In [99]:
df632.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5170015 entries, 0 to 5170014
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   User_Id           object
 1   Items_Count       int32
 2   Item_Id           float64
 3   Item_Name         object
 4   Playtime_Forever  float64
dtypes: float64(2), int32(1), object(2)
memory usage: 177.5+ MB

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49186 entries, 0 to 49185
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   User_Id             49186 non-null  object
 1   Item_Id             49186 non-null  int8
 2   Recommend           49186 non-null  bool
 3   Sentiment Analysis  49186 non-null  int8
 4   año                 49186 non-null  int8
dtypes: bool(1), int8(3), object(1)
memory usage: 576.5+ KB

In [89]:
df

                 User_Id  Item_Id  Recommend  Sentiment Analysis  año
0      76561197970982479      -30       True                   2  -37
1      76561197970982479      -72       True                   2  -37
2      76561197970982479      102       True                   2  -37
3                js41637      -38       True                   2  -34
4                js41637      -28       True                   2  -35
...                  ...      ...        ...                 ...  ...
49181            wayfeng      -38       True                   1  -33
49182  76561198251004808       28       True                   2  -33
49183        72947282842      -38       True                   0  -33
49184          ApxLGhost      -38       True                   2  -33
49185  76561198267374962       48       True                   2  -33

[49186 rows x 5 columns]

In [101]:
import os

size = os.path.getsize('User_items_reducido_32.parquet.gz')

print(f"El tamaño del archivo comprimido es de {size / 1024**2:.2f} MB")

El tamaño del archivo comprimido es de 23.78 MB

In [93]:
df145 = pd.read_parquet('User_items_reducido_32.parquet')
df145

,User_Id,Items_Count,Item_Id,Item_Name,Playtime_Forever
0,76561197970982479,277,10.0,Counter-Strike,6.0
1,76561197970982479,277,20.0,Team Fortress Classic,0.0
2,76561197970982479,277,30.0,Day of Defeat,7.0
3,76561197970982479,277,40.0,Deathmatch Classic,0.0
4,76561197970982479,277,50.0,Half-Life: Opposing Force,0.0
...,...,...,...,...,...
5170010,76561198329548331,7,373330.0,All Is Dust,0.0
5170011,76561198329548331,7,388490.0,One Way To Die: Steam Edition,3.0
5170012,76561198329548331,7,521570.0,You Have 10 Seconds 2,4.0
5170013,76561198329548331,7,519140.0,Minds Eyes,3.0
5170014,edward_tremethick,0,NaN,None,NaN

In [94]:
df145.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5170015 entries, 0 to 5170014
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   User_Id           object
 1   Items_Count       int32
 2   Item_Id           float64
 3   Item_Name         object
 4   Playtime_Forever  float64
dtypes: float64(2), int32(1), object(2)
memory usage: 177.5+ MB

In [103]:
df7 = pd.read_parquet('User_reviews_reducido_32.parquet')
df8 = pd.read_parquet('Output_steam_games_reducido_32.parquet')
df9 = pd.read_parquet('User_items_reducido_32.parquet')
merged_df = pd.read_parquet('Top 3 Desarrolladores.parquet')
merged_df5 = pd.read_parquet('User_data.parquet')
merged_df10 = pd.merge(df8, df9, on='Item_Id')
df_nuevo = merged_df10.drop(columns=['Item_Id','App_name','Price','Developer','Items_Count','Item_Name'])
df_f1 = df8[["Item_Id", "Price","Developer","Release_year"]]
df_merged123 = pd.merge(df8, df7, on='Item_Id') 
df_limpio = df_merged123[['User_Id', 'Item_Id','Developer','Release_year','Sentiment Analysis']]

In [104]:
def UserForGenre(genero):
    if not genero in df_nuevo.columns:
        return f"El género {genero} no existe en la base de datos."
    
    df_genre = df_nuevo[df_nuevo[genero] == 1]

    usur_mas_horas = df_genre.groupby("User_Id")["Playtime_Forever"].sum().idxmax()

    filtro_usur = df_genre[df_genre["User_Id"] == usur_mas_horas]

    horas_jugXaño = filtro_usur.groupby("Release_year")["Playtime_Forever"].sum()

    Horas_por_año = {}
    for clave, valor in horas_jugXaño.items():
        clave_formateada = f'Año: {int(clave)}'
        valor_formateado = int(valor)
        Horas_por_año[clave_formateada] = valor_formateado
        yield

    del df_genre, filtro_usur, horas_jugXaño
    return {"Usuario con más horas jugadas": usur_mas_horas, "Horas jugadas por año": Horas_por_año}

In [106]:
UserForGenre("Action")

In [109]:
df9

,User_Id,Items_Count,Item_Id,Item_Name,Playtime_Forever
0,76561197970982479,277,10.0,Counter-Strike,6.0
1,76561197970982479,277,20.0,Team Fortress Classic,0.0
2,76561197970982479,277,30.0,Day of Defeat,7.0
3,76561197970982479,277,40.0,Deathmatch Classic,0.0
4,76561197970982479,277,50.0,Half-Life: Opposing Force,0.0
...,...,...,...,...,...
5170010,76561198329548331,7,373330.0,All Is Dust,0.0
5170011,76561198329548331,7,388490.0,One Way To Die: Steam Edition,3.0
5170012,76561198329548331,7,521570.0,You Have 10 Seconds 2,4.0
5170013,76561198329548331,7,519140.0,Minds Eyes,3.0
5170014,edward_tremethick,0,NaN,None,NaN

In [115]:
df9 = df9.drop(columns=['Items_Count'])

In [116]:
df9.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5170015 entries, 0 to 5170014
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   User_Id           object
 1   Item_Id           float64
 2   Item_Name         object
 3   Playtime_Forever  float64
dtypes: float64(2), object(2)
memory usage: 157.8+ MB

In [114]:
df9.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5170015 entries, 0 to 5170014
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   User_Id           object
 1   Items_Count       int32
 2   Item_Id           float64
 3   Item_Name         object
 4   Playtime_Forever  float64
dtypes: float64(2), int32(1), object(2)
memory usage: 177.5+ MB

In [110]:
df002 = df9.drop(columns=['Items_Count'])

In [111]:
df002.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5170015 entries, 0 to 5170014
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   User_Id           object
 1   Item_Id           float64
 2   Item_Name         object
 3   Playtime_Forever  float64
dtypes: float64(2), object(2)
memory usage: 157.8+ MB

In [112]:
import gc

In [123]:
import pandas as pd
import numpy as np


def userdata(user_id):
    # Leer los DataFrames necesarios
    merged_df5 = pd.read_parquet('User_data.parquet', columns=['User_Id', 'Price', 'Recommend'])
    df9 = pd.read_parquet('User_items_reducido_32.parquet', columns=['User_Id'])

    if type(user_id) == int:
        user_id = str(user_id)

    if not user_id in merged_df5['User_Id'].values or not user_id in df9['User_Id'].values:
        return f"El user_id {user_id} no existe en la base de datos u.u."

    # Filtrar los DataFrames por user_id
    user_data = merged_df5[merged_df5['User_Id'] == user_id]
    user_items = df9[df9['User_Id'] == user_id]

    # Calcular la cantidad de dinero gastado por el usuario
    dinero_gastado = np.dot(user_data['Price'], user_data['Recommend'])

    # Calcular el porcentaje de recomendación en base a reviews.recommend
    recomendacion = user_data['Recommend'].sum()
    porcentaje_recomendacion = recomendacion / user_data.shape[0] * 100

    # Calcular la cantidad de items
    cantidad_de_items = user_items.shape[0]

    # Crear un diccionario con los resultados
    resultados = {
        'Cantidad de dinero gastado': dinero_gastado,
        'Porcentaje de recomendación': porcentaje_recomendacion,
        'Cantidad de items': cantidad_de_items
    }
    del merged_df5, df9, user_data, user_items
    gc.collect()
    return resultados

In [126]:
%memit userdata(76561197970982479)

peak memory: 496.91 MiB, increment: 93.56 MiB

In [125]:
%load_ext memory_profiler

In [127]:
df7 = pd.read_parquet('User_reviews_reducido_32.parquet')
df8 = pd.read_parquet('Output_steam_games_reducido_32.parquet')
df9 = pd.read_parquet('User_items_reducido_32.parquet')
merged_df = pd.read_parquet('Top 3 Desarrolladores.parquet')
merged_df5 = pd.read_parquet('User_data.parquet')
merged_df10 = pd.merge(df8, df9, on='Item_Id')
df_nuevo = merged_df10.drop(columns=['Item_Id','App_name','Price','Developer','Items_Count','Item_Name'])
df_f1 = df8[["Item_Id", "Price","Developer","Release_year"]]
df_merged123 = pd.merge(df8, df7, on='Item_Id') 
df_limpio = df_merged123[['User_Id', 'Item_Id','Developer','Release_year','Sentiment Analysis']]
def userdata(user_id):
    
    if type(user_id) == int:
        user_id = str(user_id)

    
    if not user_id in merged_df5['User_Id'].values or not user_id in df9['User_Id'].values:
        return f"El user_id {user_id} no existe en la base de datos u.u."

    user_data = merged_df5[merged_df5['User_Id'] == user_id]

    user_items = df9[df9['User_Id'] == user_id]

    # Calcular la cantidad de dinero gastado por el usuario
    dinero_gastado = user_data['Price'].sum()

    # Calcular el porcentaje de recomendación en base a reviews.recommend
    recomendacion = user_data['Recommend'].sum()
    porcentaje_recomendacion = recomendacion / len(user_data) * 100

    # Calcular la cantidad de items
    cantidad_de_items = user_items['Item_Id'].nunique()

    # Crear un diccionario con los resultados
    resultados = {
        'Cantidad de dinero gastado': dinero_gastado,
        'Porcentaje de recomendación': porcentaje_recomendacion,
        'Cantidad de items': cantidad_de_items
    }
    del user_data, user_items
    gc.collect()
    return resultados

In [128]:
%memit userdata(76561197970982479)

peak memory: 1950.98 MiB, increment: 0.29 MiB

In [129]:
def UserForGenre(genero):
    # Leer los DataFrames necesarios
    df = pd.read_parquet(['User_reviews_reducido_32.parquet', 'Output_steam_games_reducido_32.parquet', 'User_items_reducido_32.parquet', 'Top 3 Desarrolladores.parquet', 'User_data.parquet'])
    
    # Combinar los DataFrames necesarios
    df_merged = pd.merge(df[1], df[2], on='Item_Id')
    df_nuevo = df_merged.drop(columns=['Item_Id','App_name','Price','Developer','Items_Count','Item_Name'])
    df_f1 = df[1][["Item_Id", "Price","Developer","Release_year"]]
    df_limpio = pd.merge(df[1], df[0], on='Item_Id')[['User_Id', 'Item_Id','Developer','Release_year','Sentiment Analysis']]
    
    # Realizar la operación de agrupación
    if not genero in df_nuevo.columns:
        return f"El género {genero} no existe en la base de datos."
    
    df_genre = df_nuevo[df_nuevo[genero] == 1]
    usur_mas_horas = df_genre.groupby("User_Id")["Playtime_Forever"].sum().idxmax()
    filtro_usur = df_genre[df_genre["User_Id"] == usur_mas_horas]
    horas_jugXaño = filtro_usur.groupby("Release_year")["Playtime_Forever"].sum().to_dict()
    
    # Liberar la memoria utilizada por los DataFrames que ya no se necesitan
    del df, df_merged, df_nuevo, df_f1, df_limpio, df_genre, filtro_usur, horas_jugXaño
    gc.collect()
    
    # Devolver los resultados
    return {"Usuario con más horas jugadas": usur_mas_horas, "Horas jugadas por año": horas_jugXaño}

In [ ]:
def UserForGenre(genero):
    if not genero in df_nuevo.columns:
        return f"El género {genero} no existe en la base de datos."
    
    df_genre = df_nuevo[df_nuevo[genero] == 1]

    usur_mas_horas = df_genre.groupby("User_Id")["Playtime_Forever"].sum().idxmax()

    filtro_usur = df_genre[df_genre["User_Id"] == usur_mas_horas]

    horas_jugXaño = filtro_usur.groupby("Release_year")["Playtime_Forever"].sum()

    registro = horas_jugXaño.to_dict()

    Horas_por_año = {}
    for clave, valor in registro.items():
        clave_formateada = f'Año: {int(clave)}'
        valor_formateado = int(valor)
        Horas_por_año[clave_formateada] = valor_formateado
    del df_genre, filtro_usur, horas_jugXaño
    gc.collect()
    return {"Usuario con más horas jugadas": usur_mas_horas, "Horas jugadas por año": Horas_por_año}

In [ ]:
UserForGenre("Action")

In [2]:
import pandas as pd
import pyarrow.parquet as pq
import gc

def top_desarrolladores_recomendados(year):
    # Leer los archivos Parquet necesarios
    df8 = pq.read_table('Output_steam_games_reducido_32.parquet').to_pandas()
    df9 = pq.read_table('User_items_reducido_32.parquet').to_pandas()
    merged_df = pq.read_table('Top 3 Desarrolladores.parquet').to_pandas()
    
    # Realizar las operaciones necesarias con los DataFrames
    merged_df10 = pd.merge(df8, df9, on='Item_Id')
    df_year = merged_df[merged_df['year'] == year]
    df_count = df_year[df_year['Recommend'] == True][df_year['Sentiment Analysis'] == 2].groupby('Developer')['App_name'].count().reset_index()
    top_desarrolladores = df_count.sort_values('App_name', ascending=False).head(3)['Developer'].tolist()

    # Eliminar los DataFrames que ya no se necesitan
    del df8, df9, merged_df, merged_df10, df_year, df_count
    gc.collect()

    # Devolver el top 3 de desarrolladores
    return top_desarrolladores

In [3]:
top_desarrolladores_recomendados(2015)

C:\Users\baby_\AppData\Local\Temp\ipykernel_4884\1525295422.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_count = df_year[df_year['Recommend'] == True][df_year['Sentiment Analysis'] == 2].groupby('Developer')['App_name'].count().reset_index()

['Valve', 'Facepunch Studios', 'Smartly Dressed Games']

In [1]:
df7 = pd.read_parquet('User_reviews_reducido_32.parquet')
df8 = pd.read_parquet('Output_steam_games_reducido_32.parquet')

NameError: name 'pd' is not defined

In [6]:
df_merged69 = pd.merge(df8, df7, on='Item_Id')

In [7]:
df_limpio = df_merged69[['User_Id', 'Item_Id','Developer','Release_year','Sentiment Analysis']]

In [8]:
df_limpio.to_parquet('Developer Analysis.parquet')